### ISSUE TITLE
feature: benchmarks and performance profiling

### ISSUE THREAD

**Issue by deekerno** [FuelLabs/fuel-indexer#1034]
As we get closer to a `v1.0` of the indexer, we should begin to quantify the performance of various parts of the indexer so that we can track improvements and prevent regressions. In order to do so, I suggest the use of [`criterion.rs`](https://github.com/bheisler/criterion.rs), which is the most popular crate for benchmarking at this time; it runs statistical analyses on the performance of benchmarked code, generates graphs, and doesn't require a nightly version.

When benchmarking the indexer, we should _try_ to test the smallest functionality, if possible. Of course, that may be easier said than done for certain aspects, i.e. testing WASM-centric functions; in that case, we should test said aspect but still try to minimize the tested area.

#### `fuel-indexer`
- `run_executor`
- `put_object`
- `get_object`

#### `fuel-indexer-api-server`
- Asset registration
- Graph querying

#### `fuel-indexer-database`
- Execution of user queries at different complexity levels

#### `fuel-indexer-graphql`
- Dynamic schema generation
- GQL -> SQL layer

#### `fuel-indexer-schema`
- GraphQL schema parsing

**Comment by ra0x3** [comment]
@deekerno I see this as two things:
- Short term project: explorer performance
- Long term project: performance of more general indexer components (e.g., compilation, api-server, etc)

For the. "short term project", I'd give that "High" priority.

**Comment by deekerno** [comment]
> @deekerno I see this as two things:
> 
>     * Short term project: explorer performance
> 
>     * Long term project: performance of more general indexer components (e.g., compilation, api-server, etc)
> 
> 
> For the. "short term project", I'd give that "High" priority.

Heard that. So what do you think about doing the following for now?:

- fuel-indexer
-- run_executor
-- put_object
-- get_object

- fuel-indexer-database
-- Execution of user queries at different complexity levels
