### ISSUE TITLE
Remove GraphQL web API

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#1066]
- We don't have the team resources to support proper GraphQL at this time, and we can't support HackQL anymore
  - HackQL lacks functionality and requires too many resources to maintain even what little functionality we have
- We need to remove all references to the indexer's GraphQL web API 
- This work is currently blocked by https://github.com/FuelLabs/fuel-indexer/issues/1047
- This would also require updating all docs and removing all GraphQL web API references from docs
- **This would not effect our usage of GraphQL schema to build indexer modules**
- This would only effect our GraphQL usage on the web API, we aren't touching anything else related to the web API

**Comment by SilentCicero** [comment]
Before we do this we should also consider a heavier use of a generator pattern here. We are likely doing far too much in runtime. Doing more at compile time would likely allow us to keep certain functionality without the headache.
