### ISSUE TITLE
start_block not working as expected when resumable flag is set

### ISSUE THREAD

**Issue by lostman** [FuelLabs/fuel-indexer#1080]
If I configure an indexer with the following:

```
start_block: 8000
resumable: true
```

or

```
start_block: 8000
resumable: false
```

`fuel-indexer` starts fetching blocks from block `1`, fetching all blocks, while the indexer ignores all blocks until block `8000`.

I need to remove `resumable` from the manifest for the start block to be respected.

**Comment by ra0x3** [comment]
Fixed in https://github.com/FuelLabs/fuel-indexer/pull/1081
