### ISSUE TITLE
Trim down CI time

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#1095]
- CI times are as follows
  - PR: ~35 mins
  - Release: ~1 hour
  - Version bump: ~35 mins
  - Merge to master: ~35 mins
- [ ] PR CI time is really long, can't think of ways to get that down with bigger machines
  - We're building a ton of crates in parallel
- [ ] Build and test examples in parallel
  - There's no reason that examples have to be tested sequentially
- [ ] When we create a version bump PR we can skip `cargo-e2e-and-integration-tests`
- [ ] On release, we need to publish each crate in parallel
  - We could save a _ton_ of release CI time here
- [ ] On release, do not publish docker image
  - The docker image for a release would've just been published by the version bump PR
  - We're effectively publishing the same image twice
  - This combined with publishing crates in parallel could get our release action time down to ~10 mins

Feel free to add any info I may have missed

**Comment by ra0x3** [comment]
@deekerno @lostman 
- What do you guys think of just not doing any `cargo build` or `clippy` steps on (1) release (2) version bump PRs, and (3) merges to master
- I realize that's playing a little loosely - but I haven't seen a situation in a long time where either of those steps mysteriously breaks due to weird changes. Might be a chance to get these times down to < 7 mins. Just an idea

**Comment by deekerno** [comment]
I think that's fine. We don't allow any merges to `develop` without passing the CI suite anyways, so I think it's a fair tradeoff. And most times, the only errors that we have in those three scenarios are errors specific to those stages, e.g. `cargo publish` or versioning problems.
