### ISSUE TITLE
Add a new "Basic Usage" example

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#110]
- This might be covered by https://github.com/FuelLabs/fuel-indexer/issues/101
- The current example included in the "Basic Usage" doesn't include the context of an example
  - An example includes contracts, schema, configs, all of the supporting components that make an indexer work
- So if you try to follow the "Basic Usage" section as it stands...it won't really work
- We should update this to include something that constitutes true "Basic Usage" -- again, this is pretty much the same as https://github.com/FuelLabs/fuel-indexer/issues/101

Additional context
- The existing stuff in the current "Basic Usage" _does work_ -- it just isn't fully self-contained -- it requires info that isn't included.
  - This missing info basically amounts to an example
  - We currently have 2 fully-functioning examples so users can still reference the "Examples" section
    - Which is why I'm just choosing to remove this section (for now)

**Comment by deekerno** [comment]
@ra0x3 Go for it! Honestly, I'd forgotten that I assigned myself, and it sounds like your example is better than what I was going to do anyways.
