### ISSUE TITLE
Polish/update all plugin command

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#1135]
- We need to take a look over each plugin command and make sure it's as simple as possible
- This means reducing the number of options on each command where possible
- Ideally a user should just be able to run `forc index --help` and `forc index [command]--help` to completely understand how to use the plugin
- This also applies to `forc index postgres`

- `forc index`
  - `forc index start`
  - `forc index build`
  - `forc index deploy`
  - `forc index init`
  - `forc index new`
- `forc postgres`
  - `forc index remove`
  - `forc postgres create`
  - `forc postgres stop`
  - `forc postgres start`
  - `forc postgres drop`

Additional context
- This work also includes:
  - https://github.com/FuelLabs/fuel-indexer/issues/1127
  - https://github.com/FuelLabs/fuel-indexer/issues/1069

**Comment by deekerno** [comment]
Some thoughts after a first pass:
- We can combine `forc index init` and `forc index new` into one command, perhaps under the `forc index init` name; `forc index init` (with no args) initializes a project in the current directory while `forc index init [name]` creates a folder `name` in the current directory. Passing a path would initialize an indexer project at that location. Additionally, we could mirror [`cargo init`](https://doc.rust-lang.org/cargo/commands/cargo-init.html) where possible. As far as generating a namespace for the user, we could use something like [`whoami`](https://github.com/ardaku/whoami) and use their username to fill in the namespace for them, if it's not presented.
- `forc index build`: I think we can remove the `--profile` flag; [profiles](https://doc.rust-lang.org/cargo/reference/profiles.html) are for adjusting compiler optimizations and the like, which regular users should not have to care about. Similarly, I think we can remove the `--target` flag and just enforce `wasm32-unknown-unknown` for now unless `--native` is passed. Overall, we want to make the tool as friendly as possible for regular users and power users can always run the `cargo build` command with all of its available options if they don't feel that `forc index build` is right for them. We can remove the same build options from `forc index deploy` as well.
- `forc index check`: We have the port and URL flags, but the latter has a default that includes both the endpoint and port. Perhaps we can just do the URL flag and instruct users to include the port on it as well?
- `forc index start`: This is pretty much dictated by `fuel-indexer run`.
- `forc postgres create`: It seems that I cannot get `-h` or `--help` to run correctly as the program panics immediately. This will need to be fixed.

@ra0x3, @lostman: Any thoughts here?

**Comment by ra0x3** [comment]
@deekerno 
- Combining `new` and `init` - SGTM 👌🏽 
- Removing `--profile` and `--target` from `forc index build`
  - `--profile` definitely 👌🏽 
  - `--target` 🤔  Does this mean we will only ever be able to run `forc index build` if you're in the indexer directory?
- I think we can remove `fuel-indexer` from `forc index check` altogether
  - That's more for dependencies - not checking service status
- Fixing `forc index postgres` panic 👌🏽

**Comment by deekerno** [comment]
@ra0x3 
> 
>     * Combining `new` and `init` - SGTM 👌🏽
> 
>     * Removing `--profile` and `--target` from `forc index build`
>       
>       * `--profile` definitely 👌🏽
>       * `--target` 🤔  Does this mean we will only ever be able to run `forc index build` if you're in the indexer directory?
> 
>     * I think we can remove `fuel-indexer` from `forc index check` altogether
>       
>       * That's more for dependencies - not checking service status
> 
>     * Fixing `forc index postgres` panic 👌🏽

Nah, `--target` pertains to things like `wasm32-unknown-unknown`; you may be thinking of `--target-dir` which lets you indicate the location of your artifact folder, or `--path` which indicates the location of the project folder.

**Comment by ra0x3** [comment]
@deekerno 
- But I'm saying

If I `forc index build` from `current_dir/` but the indexer project is in `target_dir/` is that `--target` required (I know in cargo it would be). But maybe we're actually `cd` changing directories during `forc index build`? 

We have that `.cargo` config in indexer directories to specify the target I know

**Comment by deekerno** [comment]
Hmmm, that's a good question; I'll check on that and see what the answer is. In any case, we either compile to WASM or native, so if we already have the `--native` flag, then I feel that we can get away with assuming the `wasm32-unknown-unknown` target (even if `target_dir` is in a different place) and then changing that target if the `--native` flag is included.
