### ISSUE TITLE
Make manifest `contract_id` work with both namespaced and non-namespaced contract IDs

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#1137]
- Namespaced contract ID: `fuels....`
- Not namespaced contract ID: `0x0000...`
- The `contract_id` field in the indexer manifest should work with both 
- We should also update the default indexer manifest with an additional comment for the `contract_id` field specifying that we support both contract ID types
  - That is [here](https://github.com/FuelLabs/fuel-indexer/blob/develop/plugins/forc-index/src/defaults.rs#L111)
- If we implement this, we can close https://github.com/FuelLabs/fuel-indexer/issues/983

**Comment by dadepo** [comment]
@ra0x3 I am thinking of taking a stab at this next. What would you say is the best way to create a scenario involving contract ID that does not have the fuel namespace? and how to show it does not work?

**Comment by ra0x3** [comment]
@dadepo 

### Background

- The namespaced contract ID uses the bech32 encoding format. 
- You can call `.hash()` on a `Bech32ContractId`  to get the underlying `Bytes32`. 
  - You can also convert this `Bytes32` to and from `ContractId`  ([example](https://rust.fuel.network/v0.46.0/types/bech32.html?highlight=bech32#bech32))


> - The main benefit of the bech32 encoding is that it includes a includes a built-in error-detection mechanism which can guard against typos.
> - On the SDK side, we had a discussion whether we should support creating an address from either format because other parts of the ecosystem, like fuel-core usually output ContractId. However, that would mean that we loose the main benefit of bech32, so we decided to force the user to use the bech32 format.

- I believe someone at Fuel is doing work on a CLI tool that allows users to easily convert to-and-from either type

### Implementation
- The relevant part of the code is [here](https://github.com/FuelLabs/fuel-indexer/blob/develop/packages/fuel-indexer-macros/src/indexer.rs#L253)
- As far as "success criteria" - you should be able to just change the `fuel-indexer-test` indexer's [`contract_id` parameter here](https://github.com/FuelLabs/fuel-indexer/blob/develop/packages/fuel-indexer-tests/indexers/fuel-indexer-test/fuel_indexer_test.yaml) to its `ContractId` (non-namespaced) equivalent - all integration tests should still work :)
