### ISSUE TITLE
Revamp our docs

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#1174]
A list of additions that need to make it into the book

- [x] README
  - Short & sweet & to the point, nothing more to do here
 
- [Components section](https://fuellabs.github.io/fuel-indexer/master/project-components/index.html)
  - [ ] [The `Module` example](https://fuellabs.github.io/fuel-indexer/master/project-components/module.html) should be an example.

- [Service section](https://fuellabs.github.io/fuel-indexer/master/getting-started/starting-the-fuel-indexer.html)
  - [ ] Create table to show port usage
    - [Example](https://thegraph.com/docs/en/network/indexing/#graph-node)

- [GraphQL section](https://fuellabs.github.io/fuel-indexer/master/graphql/index.html)
  - [x] Document all GraphQL scalars

- [The Indexing section](https://fuellabs.github.io/fuel-indexer/master/indexing/index.html)
  - [ ] Include a full module example, not just the handler function (else it's harder to understand what's being conveyed)
    - For every item

- [x] Move `Data Types` section to the `Database` section?

### New book layout

❌  = Change needs to be made
✅  = Looks good

- Getting started ✅ 
  - Dependencies ✅ 
  - Quickstart ✅ 
  - Hello World ❌ 
    - This is a pretty complicated example for "hello world"
    - Hello world should be as simple as the quickstart
  - Starting the Fuel Indexer ❌ 
    - This needs to changed to "Fuel Indexer Node" or something similar
      - Can put the port/service table here
  - Reference Guide ✅ 
    - Project Components
      - Manifest ✅ 
      - Schema ❌ 
        - Should provide a link to the "GraphQL Scalars" section mentioned above ☝🏽 
      - Module  ❌ 
        - Update as mentioned above ☝🏽 
    - Indexing ❌  (new layout should be:)
      - Blocks
        - With explanation and example
      - Transactions
        - With explanation and example
      - Receipts (with each type nested below)
        - Keep the same list of receipts, but should include an example _for each_
    - Data type ❌ 
      - Remove this section
    - GraphQL ✅ 
      - Add section for scalars (as mentioned above ☝🏽 )
      - Add section for "Entities"
        - Here we explain the usage of `::get_or_create()` and `::new()`
      - Directives ✅ 
      - API Server ❌ 
        -  This should only be discussed with regard to being a GraphQL server - not a general web server
        - Any general web server comments should be moved to "Starting the Fuel indexer" section
      - Add a section called "Relationships" that explains GraphQL foreign key usage
    - Queries  ❌
      - Keep as-is for now but nest under GraphQL section
    - Database ✅
      - Foreign Keys ❌
        - Remove this
      - ID types ❌
        - Remove this
      - Data types ❌
        - Include the mapping of scalar -> db type here
     - forc-index ✅
       - Largely keep these as-is
     - forc-index-postgres ✅
       - Largely keep these as-is
     - Authentication ❌
       - Can keep what we have but should add a full example with commands and output 
    
We can add more as we think of things

**Comment by ra0x3** [comment]
@deekerno @lostman I went through and made some notes, feel free to comment on what changes you think should be made.

**Comment by deekerno** [comment]
Thoughts:
- We also need to add information on `::get_or_create()` as well.
- Agreed on the full indexer module example.
- Maybe we should add `Data Types` in to the Indexing section? My reasoning is that users may not touch the database as much as they may work on the handler functions themselves.
- Agreed on generally having more examples

**Comment by ra0x3** [comment]
@deekerno 
- Updated the layout with an "Entities" section under GraphQL
- The thing about "Data Types" is that since it maps GraphQL scalars to database types, and since we don't introduce GraphQL scalars until the GraphQL section, I don't think we should put the database type --> scalar type mapping before the GraphQL section
