### ISSUE TITLE
Stop an indexer, or report an error, when database operation fails: "TypeId(-8293274664658733968) not found in tables: {}"

### ISSUE THREAD

**Issue by lostman** [FuelLabs/fuel-indexer#1176]
If an indexer is deployed with a schema that doesn't match, every call to `put_object` fails:

```
2023-08-02T09:21:59.865028Z ERROR fuel_indexer::database: 143: TypeId(-8293274664658733968) not found in tables: {}.

Does the schema version in SchemaManager::new_schema match the schema version in Database::load_schema?

Do your WASM modules need to be rebuilt?
```

See #1175 for a way to trigger this.

This error is not reported to the indexer or the `fuel-indexer` service. Thus, the indexer continues running.

EDIT: this will be fixed by #1337.

**Comment by ra0x3** [comment]
Closing as fixed in #1337
