### ISSUE TITLE
Indexer futures are never retired

### ISSUE THREAD

**Issue by lostman** [FuelLabs/fuel-indexer#1231]
I have never seen this message appear in the logs:

https://github.com/FuelLabs/fuel-indexer/blob/ee28a5e851004beea5863d3e5b54679d0cef8ab6/packages/fuel-indexer/src/service.rs#L274

So, I added a print statement to see what happens:

```
futs.push(handle);

info!("futs.len {}", futs.len());
```

And after running `forc index deploy` on a loop for a while:

```
2023-08-09T12:00:56.293765Z  INFO fuel_indexer::service: 325: futs.len 39
```

After the kill switch is flipped, `run_executor` loop completes.

Why doesn't the future? `JoinHandle` should return `()`, and we should see the `Retired...` message.

**Comment by ra0x3** [comment]
Relevant https://github.com/FuelLabs/fuel-indexer/pull/487

**Comment by lostman** [comment]
@ra0x3, we may want to go back to `abort()` for stopping indexers.

There is no need to `await` spawned tasks, `tokio` runs them automatically:

https://docs.rs/tokio/latest/tokio/task/fn.spawn.html

> The provided future will start running in the background immediately when spawn is called, even if you don’t await the returned JoinHandle.

In any case, something is off if the futures never complete.

**Comment by ra0x3** [comment]
- This is an open issue that's labeled as a bug, but hasn't had a PR in two weeks
- A "bug" is something that should be resolved ASAP
- Are we sure this is a "bug" @lostman ?
  - If so let's get working on this (@deekerno who is assigned)
  - If not, let's close this

**Comment by lostman** [comment]
This is closed now by JoinSet PR.
