### ISSUE TITLE
strings more str[32] 

### ISSUE THREAD

**Issue by PaulZhemanov** [FuelLabs/fuel-indexer#1232]
Hi. How do you index strings longer than 32 characters?

**Comment by ra0x3** [comment]
@PaulZhemanov We use the `Charfield` scalar for indexing strings.

```graphql 
type Person {
  id: ID!
  name: Charfield! # Can be up to 255 characters long
}
```

In your indexer handler you can convert `SizedAsciiString` (the SDK's string type) to indexer string types by just doing

```rust 
mod my_module {
  fn my_handler(event: MyEvent) {
    // Assuming event.name is str[32]
    let p = Person::new(event.name.to_string());
  }
}
```

Let me know if this helps. Also gonna move this to a discussion :)
