### ISSUE TITLE
Strange error during deployment of indexer

### ISSUE THREAD

**Issue by chlenc** [FuelLabs/fuel-indexer#1240]
# Strange error during deployment of indexer
Hi guys, I still working on indexing of data in my [contract-based orderbook](https://github.com/compolabs/spark/blob/beta-3/contracts/orderbook/src/main.sw) and trying use `type OrderEntity @entity ` inside of `type CreateOrderEntity @entity ` as an entity (like to make link to OrderEntity on CreateOrderEntity), but after this changes https://github.com/compolabs/spark/commit/e9416946924a8810fbc401e525e6683723464d3c it fail with that error during deployment
```
{
  "details": "Schema error: Error from sqlx: Database(\n    PgDatabaseError {\n        severity: Error,\n        code: \"42601\",\n        message: \"syntax error at or near \\\"order\\\"\",\n        detail: None,\n        hint: None,\n        position: Some(\n            Original(\n                162,\n            ),\n        ),\n        where: None,\n        schema: None,\n        table: None,\n        column: None,\n        data_type: None,\n        constraint: None,\n        file: Some(\n            \"scan.l\",\n        ),\n        line: Some(\n            1188,\n        ),\n        routine: Some(\n            \"scanner_yyerror\",\n        ),\n    },\n).",
  "success": "false"
}
```

## Toolchain
```
Default host: aarch64-apple-darwin
fuelup home: /Users/alexey/.fuelup

installed toolchains
--------------------
beta-3-aarch64-apple-darwin
latest-aarch64-apple-darwin (default)
hotfix
my-custom-toolchain

active toolchain
-----------------
latest-aarch64-apple-darwin (default)
  forc : 0.42.1
    - forc-client
      - forc-deploy : 0.42.1
      - forc-run : 0.42.1
    - forc-doc : 0.42.1
    - forc-explore : 0.28.1
    - forc-fmt : 0.42.1
    - forc-index : 0.19.3
    - forc-lsp : 0.42.1
    - forc-tx : 0.42.1
    - forc-wallet : 0.2.4
  fuel-core : 0.18.3
  fuel-indexer : 0.19.3

fuels versions
---------------
forc : 0.43
```

## How to reproduce the bug
```
 git clone https://github.com/compolabs/spark.git
 cd spark
 git checkout beta-3 
 cd spark-indexer/  
 forc index build

```

**Comment by deekerno** [comment]
Hey @chlenc! Can you provide your schema?

**Comment by deekerno** [comment]
@chlenc I looked at your schema using the link provided and it may be that the `order` field of `CreateOrderEntity` is colliding with the reserved `ORDER BY` keyword. Try changing that field name to something else and deploying again.

**Comment by ra0x3** [comment]
@chlenc https://www.ibm.com/docs/en/psfa/7.2.1?topic=keywords-sql-common-reserved-words

**Comment by chlenc** [comment]
@deekerno @ra0x3 
You guys right, Thanks
