### ISSUE TITLE
Create block explorer data mitigation plan

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#1248]
- The block explorer will be the source of truth for Fuel on-chain data
- It is expected to be 100% accurate, 24 hours per day, 7 days per week, 52 weeks per year
- Even under the best circumstances there's still a non-zero probability that some data point will be incorrect according to the indexer
- We need to put a plan in place (a playbook) for when the time comes that we have to either:
  - Correct some single data point
  - Correct some set of data points
  - Walk back the explorer's indices to some block and reindex from this new starting point with some change

**Comment by Voxelot** [comment]
Without time-traversal (i.e. tracking diffs of every db change) to rewind back to a good state, would the most straightforward solution be simply re-indexing everything after the logic is corrected?

**Comment by ra0x3** [comment]
@Voxelot

- Very very rough playbook WIP [here](https://www.notion.so/fuellabs/Block-Explorer-Playbook-e8a38ed5e1f34889939980db3c2ff71a) which might add some clarity
- Essentially defining some shared vocabulary, stakeholders, incident types, priority, and the rough playbook for what to do when

**Comment by ra0x3** [comment]
Closing as finished (for now), though we might make updates in the future. @Voxelot I'll share during our sync
