### ISSUE TITLE
Optimize CI workflow for general development PRs

### ISSUE THREAD

**Issue by deekerno** [FuelLabs/fuel-indexer#1252]
I have some thoughts for adjustments to general development PRs; generally, the CI workflow for a development PR would be as follows:

_First group_
- set-env-vars
- docs-tests
- Cargo.toml check
- `cargo fmt --check` on the workspace

_Second group_
- `cargo clippy --locked --no-default-features` on the workspace
- `cargo clippy --locked --all-targets --all-features` on the workspace
- Unit tests
- E2E and integration tests
-- This would include the optimized tests from #1194 and any new tests added as part of #1230.
- Build default indexer
- Build and test examples

This would speed up development PRs considerably as we'd be cutting about 24 jobs from our workflow by not building each package with both sets of feature flags.

Reasoning:
- [`cargo clippy` runs `cargo check`](https://github.com/rust-lang/rust-clippy/blob/c154754b74577906c5d55d57f7daeff02d6a33e7/src/main.rs#L59), which is [`cargo build` without the actual code generation process](https://doc.rust-lang.org/cargo/commands/cargo-check.html#description). I don't think we've had an error that was build-time only in a very, very long time (please correct me if I'm wrong).
-- If we're skittish about not having a build job that actually catches errors in code generation, I think we can move them to the version bump PR type as we would still be able to catch any failed builds before the publishing step.
- The E2E and integration tests generally have to compile the project in order to properly test things from end-to-end so we should be able to catch any failed builds at this step.

@ra0x3, @lostman: Thoughts?

**Comment by lostman** [comment]
@deekerno Does this means removing `cargo-verifications`?

If we want to keep these, I wonder whether keeping these as a matrix build makes sense.

Practically all code between our crates is shared. Doing these in a single job might take a little longer than each verification, but it would free up runners to do other things. Currently, much time is spent setting up runners for nearly identical builds.

I think that a single job would reduce the total CI run time by a good chunk.

**Comment by ra0x3** [comment]
@lostman @deekerno I think this https://github.com/FuelLabs/fuel-indexer/issues/1193 might be of some use (with regard to cutting down on redundant matrix builds while still testing feature flag combinations)

**Comment by deekerno** [comment]
@lostman: It does mean removing `cargo-verifications`. I believe that doing just `cargo clippy --locked --all-targets --all-features` and `cargo clippy --locked --no-default-features`, or using `cargo hack` to a combination of feature flags as @ra0x3 suggested would be a suitable replacement. In general, replacing `cargo verifications` with the aforementioned options would reduce our job count by at least 20.

**Comment by ra0x3** [comment]
@deekerno I think this is good to start working on. We're all on the same page of remove as many redundant build as possible. This would most likely include moving _all_ tests that require a fuel-indexer and/or forc-index binary (whether QA/unit/integration/whatever) to a single step - so that we only ever need to build forc-index a single time

**Comment by deekerno** [comment]
@ra0x3 Sounds great to me; I'll get started on this.
