### ISSUE TITLE
Investigate failing `TransferOut` receipt test

### ISSUE THREAD

**Issue by deekerno** [FuelLabs/fuel-indexer#1276]
The `TransferOut` receipt test currently fails as the contract is unable to transfer the asset to an address. This should be fixed to ensure that our E2E test suite properly covers all receipts.

**Comment by dadepo** [comment]
@deekerno I am thinking of looking into this next. If you've got any more background or pointers/ideas as to why the test is flaky, please do share.

**Comment by deekerno** [comment]
Hey @dadepo! Thanks for your willingness to look into this!

I don't think there's much background that isn't used as part of the test and the fixture themselves, but I'll share some information:
- This test uses the `transfer_to_address` Sway method in order to send an asset to an address. The indexer's end-to-end tests use the Rust SDK to trigger the custom Sway functions and create the necessary receipts. Since it generates an output, the fixture has historically used the `.append_variable_outputs(...)` method in the SDK call and since there is a recipient to transferred assets, the Sway method itself needs to be annotated with `#[payable]` in the contract.
-- Both of these requirements have already been fulfilled.
- I don't have any logs or an ability to check the exact error at this time, but as far as I remember, the tests fails because of an `OutOfGas` error. We typically set the amount of available gas to an inordinate amount to prevent these errors, but it seems that there may have been some sort of change in how this test should be constructed.
- My pointers:
-- _Ensure the Sway transfer method is correctly formed_: It's possible that the recommended way to transfer to an address has changed.
-- _Check if the process to call contract methods from the SDK has changed_: For this, I'd look at the documentation for the SDK or check the changelogs for `fuels-rs` to see if anything concerning contract methods has been changed.
-- _Mind the `contract_id` field in the test manifest_: If you change the Sway contract in any way, its contract ID may change. If so, you'll need to determine the new contract ID and change the test manifest file so the test indexer correctly indexes the contract.

A successful implementation should have a correctly functioning `TransferOut` test and will have the `#[ignore]` directive removed so that it is included in our test suite again.

If you need any help, let us know. Thanks! 😄

**Comment by dadepo** [comment]
@deekerno Thanks for the pointers! it was really helpful :)

Just opened a PR which I believe fixes the issue here https://github.com/FuelLabs/fuel-indexer/pull/1356
