### ISSUE TITLE
docs: create comparison page with The Graph

### ISSUE THREAD

**Issue by deekerno** [FuelLabs/fuel-indexer#1343]
As we move closer to mainnet, we should create a section that compares the Fuel indexer service with The Graph. Our project is functionally different from it, but the end result for the user is essentially the same; we should explain the differences between the two projects.

**Comment by ra0x3** [comment]
@deekerno Thankfully @Voxelot took a first-stab at this if you want to integrate some of his findings https://www.notion.so/Indexer-Feature-Matrix-24d654f1bc3d411e8371d13db90fe237
