### ISSUE TITLE
Remove `report_metrics` from indexer manifest

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#1347]
- This flag was added at a time when we thought we'd report indexer metrics of some kind
- This can be removed, as we're not going that route

**Comment by dadepo** [comment]
I'll look into picking this next. @ra0x3 any potential spooky action at a distance removing this might cause? :)

**Comment by ra0x3** [comment]
@dadepo 
- A simple grep for `report_metrics` should do the trick. Will want to remove references from the code and the docs
  - But be warned the code might not actually be there, it might merely be a probability wave, and removing it might only cause it to "re-appear" somewhere else ;)
