### ISSUE TITLE
Find a way to get native execution to work with feature flagging

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#1393]
- Because native execution's `prelude`, and `#[tokio::main]` components are compiled, feature flagging doesn't work the same as it does for WASM execution 
- We should try to find a way for native execution to support these feature flags, same as WASM execution does
- For now, we'll just remove feature flagging (all features turned on) for native execution (this is what we've been doing in the past)

**Comment by deekerno** [comment]
I'm going to close this since we've removed native execution. We can open this back up if need be.
