### ISSUE TITLE
enhancement: add postgres connection monitoring to the QA script

### ISSUE THREAD

**Issue by lostman** [FuelLabs/fuel-indexer#1433]
### Description

We can periodically query Postgresql to see the number of active connections.

We had issuers related to too many connections before when I was benchmarking metering points, and lately: https://github.com/FuelLabs/fuel-indexer/issues/1430

```
psql -c "SELECT count(*) FROM pg_stat_activity WHERE state = 'active';"
 count
-------
     4
(1 row)
```

**Comment by ra0x3** [comment]
@lostman 
- You think it would be prudent to make this metric (number of open connections) a metric in the QA script itself?

**Comment by lostman** [comment]
I think so. If it raises linearly with the number of indexers then there's an improvement to be made somewhere.
