### ISSUE TITLE
Add a CI test to ensure the contract ID in fuel-indexer-test indexer manifest matches the contract ID of fuel-indexer-test contract

### ISSUE THREAD

**Issue by lostman** [FuelLabs/fuel-indexer#1451]
Add a CI test to ensure the contract ID in the `fuel-indexer-test` indexer manifest matches the contract ID of the `fuel-indexer-test` contract.

It is a small detail that is easy to miss

**Comment by ra0x3** [comment]
@lostman 

- Don't we have a `contract_id` specified in the test indexer manifest already? [here](https://github.com/FuelLabs/fuel-indexer/blob/develop/packages/fuel-indexer-tests/indexers/fuel-indexer-test/fuel_indexer_test.yaml#L7)
- Which will build the contract subscription check into the indexer module? [here](https://github.com/FuelLabs/fuel-indexer/blob/develop/packages/fuel-indexer-macros/src/indexer.rs#L466)
- So, in effect, if the contract IDs don't match the tests will fail?

Unless I'm missing something 🤔
