### ISSUE TITLE
Add a `--network` flag to `fuel-indexer`

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#1455]
- We very often start the service connected to beta-4
- Using `--fuel-node-host beta-4.fuel.network` and `--fuel-node-port 80` can be a bit much
- We should add a `--network` option that will automagically imply `--fuel-node-host beta-4.fuel.network` and `--fuel-node-port 90`
- Usage `fuel-indexer --run-migrations --network beta-4`

Additional context
- We should also then update all docs to reference `--network beta-4`

**Comment by deekerno** [comment]
This is a great first issue. 👌🏽 

To a would be contributor: I actually implemented this functionality in the past, but that branch is _loooooooong_ out of date. Feel free to use this updated snippet as a clue for your work:
```
lazy_static! {
    pub static ref AVAILABLE_NETWORKS: HashMap<&'static str, &'static str> =
        HashMap::from([
            ("Local Node", "127.0.0.1:4000"),
            ("Beta-4", "beta-4.fuel.network:80"),
        ]);
}
```
