### ISSUE TITLE
Errors "expected `AssetId`, found `[u8; 32]`  arguments to this function are incorrect" and "Unrecognized primitive type: `str`." during `forc index build`

### ISSUE THREAD

**Issue by chlenc** [FuelLabs/fuel-indexer#1484]
Hi guys 

I tried to build an indexer with abi of one of our spark perp contracts and got this error 
![image](https://github.com/FuelLabs/fuel-indexer/assets/35231749/c677d749-feaf-4b6e-8f30-b889dafe54cf)

after I removed str from abi, and after that I got that error (2nd screenshot)
![image](https://github.com/FuelLabs/fuel-indexer/assets/35231749/48063aa2-c0c1-46e1-b029-0e5d2927abcd)

## my toolchain
```
Default host: aarch64-apple-darwin
fuelup home: /Users/alexey/.fuelup

installed toolchains
--------------------
beta-3-aarch64-apple-darwin
beta-4-rc.2-aarch64-apple-darwin
latest-aarch64-apple-darwin
beta-4-aarch64-apple-darwin (default)
hotfix
latest-2023-09-25-aarch64-apple-darwin
latest-2023-11-15-aarch64-apple-darwin
my-custom-toolchain

active toolchain
-----------------
beta-4-aarch64-apple-darwin (default)
  forc : 0.46.1
    - forc-client
      - forc-deploy : 0.46.1
      - forc-run : 0.46.1
    - forc-doc : 0.46.1
    - forc-explore : 0.28.1
    - forc-fmt : 0.46.1
    - forc-index : 0.23.0
    - forc-lsp : 0.46.1
    - forc-tx : 0.46.1
    - forc-wallet : 0.3.0
  fuel-core : 0.20.5
  fuel-core-keygen : Error getting version string
  fuel-indexer : 0.23.0

fuels versions
---------------
forc : 0.45
forc-wallet : 0.45
```

here is my abi
[account-balance-abi.json](https://github.com/FuelLabs/fuel-indexer/files/13506648/account-balance-abi.json)

**Comment by ra0x3** [comment]
@chlenc 
- After looking into this, I _believe_ this issue is being caused by the SDK during the ABI generation phase
  - The SDK is generating its own `AssetId` which is clashing with our `AssetId`
- More discussion in https://github.com/FuelLabs/fuel-indexer/issues/1487
