### ISSUE TITLE
Resolve Sway contract `configurables` name collision issues

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#1487]
- Usage of certain types in Sway causes types to be generated in the ABI that clash with indexer scalar types
- [An example of these "certain types" usage in a contract](https://github.com/compolabs/spark-perps/blob/master/vault/src/main.sw#L23)
- For now, we will just skip deriving types from these clashing types
  - This _might_ be the actual fix but we need to revisit 

- How we discovered this:
  - SwayGang showed us a name collision error in their indexer, and after looking at their Sway contract, I saw that they're using `configurables` in the contract (which I didn't know you could do) - but is fine in general
  - So when I went and added `configurables` to our test indexer contracts, I noticed all of this

**Comment by ra0x3** [comment]
@segfault-magnet 
- Might need your help here.
- My quick fix approach was just to skip these types that have clashing names (e.g., `AssetId`)
- However, looks like this won't work because the SDK actually redefines these types in the tokens generated from the ABI JSON
- So off the top of my head there doesn't seem to be a way to have the user use `configurables` in their Sway contract with something like `AssetId` without making some non-trivial changes to a ton of indexer code

```
        #[NoStd]
        pub struct AssetId {
            pub value: ::fuels::types::Bits256,
        }
```

:(

- It feels a bit odd that we're redefining a core fuel type (`AssetId`)

**Comment by segfault-magnet** [comment]
Check the SDK version. AssetId should be the fuel core type since version `fuels` 0.49.0. 

Lemme know if it is newer than the above.

**Comment by ra0x3** [comment]
@segfault-magnet Version is `fuels = { version = "0.50", default-features = false }`

**Comment by segfault-magnet** [comment]
I tested this locally, we're resolving the type to the AssetId from fuel types. 

How can I reproduce this issue @ra0x3 ? Cannot access the link in the issue, getting 404.

**Comment by ra0x3** [comment]
@segfault-magnet 
- I have a WIP PR here https://github.com/FuelLabs/fuel-indexer/pull/1488
- If you check the `foo.txt` file, you'll see the code that I pasted above ☝🏼 
  - This file is the result of running `cargo expand` in an indexer module - so shows all the SDK expanded code
- Also happy to hop on a quick call if that makes things easier
- The changes to `main.sw` are the configurables that I added to produce this result

**Comment by segfault-magnet** [comment]
@ra0x3 the `Abigen` used in the code generation is from `fuels` `0.46`. Can you update it over in `fuel-indexer-macros`'s `Cargo.toml`? Anything after 0.49 should be ok.

@ra0x3 

Edit:
Heck since I seem to be blind, might as well add one more @ra0x3  :D

**Comment by ra0x3** [comment]
Ahh ok @segfault-magnet I see `fuels` and `fuels-code-gen` are separate. Let me try this.

**Comment by ra0x3** [comment]
@segfault-magnet Purrrffect 🐱 worked like a charm thanks!
