### ISSUE TITLE
Can we cut down on build times?

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#248]
- Title says it all
- The project takes quite a while to build due to nothing in particular other than just heavy dependencies
  - Rocksdb from fuel-core being one of the main culprits that stands out
- This task is to discuss ways in which we can lower build times by doing things like:
  - Removing unnecessary dependencies
  - Structuring dependencies in a better way
  - Using caching (I'm currently using [sccahe](https://github.com/mozilla/sccache) locally, and we're using [standard cargo caching](https://github.com/Swatinem/rust-cache) on CI)

Additional context
- I'm fairly new to Rust so any tips/tricks/rules-of-thumb would be appreciated
- I've read over https://endler.dev/2020/rust-compile-times/

**Comment by ra0x3** [comment]
CC @Voxelot on this

**Comment by Voxelot** [comment]
@mitchmindtree's fuel-core-dev nix flake drastically improves the build times of fuel-core by using precompiled version of RocksDB for the build process. You could likely make a nix flake for the fuel-indexer repo that will pull in any of the big `-sys` libs as precompiled, which will make the biggest diff.

You can also set `default-features = false` for fuel-core to disable rocksdb if you only need the in-memory db backend for testing.

**Comment by ra0x3** [comment]
@Voxelot 
- I imagine you've incorporated this nix flake into CI/locally ? Anything to read to see how you did it? I imagine the indexer will be a bit similar to fuel-core
