### ISSUE TITLE
How to cut down CI time

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#252]
- CI with e2e tests takes about 50 mins
- Specifically the `cargo-test-workspace-all-features` step (the main culprit) takes so long because it has to build the `fuel-indexer` and `fuel-indexer-test-web` packages, _then_ it has to run the test suite which requires yet another build
  - This 2-step process effectively amounts to the same time as 2 of the `cargo-build-workspace` steps back-to-back
- We're building the `fuel-indexer` and `fuel-indexer-test-web` packages in  the `cargo-test-workspace-all-features` step because the e2e tests use the indexer (via its binary) as well as a fuel-node, and web component (via their binaries)

Additional context
- I previously tried removing the web component and building the fuel-node as a test fixture, but I couldn't get this to work and didn't want it to become a PR blocker
  - I believe this setup would require some way to spin up the indexer service in a test, _then_ wait a few seconds (in a separate thread) before calling the smart contract, the waiting another few seconds before trying to find the indexed event in the DB
  - I'm sure this is possible but just require time to test/debug/research

**Comment by ra0x3** [comment]
CC @deekerno

**Comment by deekerno** [comment]
Perhaps we can pass some additional `RUSTFLAGS` into the testing steps. Looking at the [codegen section of the `rustc` book](https://doc.rust-lang.org/stable/rustc/codegen-options/index.html), there may be a few options that we can leverage; specifically:

- `codegen-units`: This splits a crate into multiple codegen units which ultimately may allow for faster compile times but less performant code. Non-incremental builds have a default value of 16. Applying this to the test runs only may help overall, and could _perhaps_ allow for more granular caching of build artifacts (I still have more research to do on how the caching mechanism for these CI actions work under the hood).
- `lto`: Link time optimization for better optimized code at the expense of longer linking time. If this flag isn't specified, then the compiler defaults to thin local LTO, which performs some basic optimization across local codegen units. This can be set to `off` to disable it.

Additionally, we could investigate using a different linker. As far as I can tell, `rustc` defaults to using `ld` as its linker on Linux-based systems. There are a number of faster options available, namely [`lld`](https://lld.llvm.org/#performance) which appears to be a fairly popular choice as of late. Furthermore, there's (allegedly) an even option in [`mold`](https://github.com/rui314/mold). The compiler supports both of these options, if we choose to explore them.

**Comment by ra0x3** [comment]
Related https://stackoverflow.com/questions/29361801/is-the-lld-linker-a-drop-in-replacement-for-ld-and-gold

**Comment by ra0x3** [comment]
Closing since https://github.com/FuelLabs/fuel-indexer/issues/269 would solve the CI time issue
