### ISSUE TITLE
Add tests for new Receipt types

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#268]
- Now that we have support for several receipt types, it would be nice to have this functionality tested
- We initially punted on testing in the relevant PRs because we wanted to make sure we were on track to complete the milestone
  - Not only this, but we also don't really know how to trigger some of these events in a Sway smart contract
- We should add a test for all added receipts functionality

Tests for:
- [x] Log
- [x] LogData
- [x] Transfer
- [ ] TransferOut
- [x] MessageOut
- [x] ScriptResult

**Comment by deekerno** [comment]
The `TransferOut` receipt requires `fuels-rs` to use `fuel-core`/`fuel-core-interfaces` v0.12 as it contains the fix for the `TRO` instruction; v0.28 of the SDK should contain this fix.

**Comment by ra0x3** [comment]
Marking this container of issues as complete (though we still have TransferOut test left - which is fine)
