### ISSUE TITLE
"Hello world" example

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#27]
- Would love to have a "Hello world" type of example that features:
  - Installing `fuel-core` and `fuel-indexer`
  - Writing a simple Sway contract (e.g., Counter)
  - Subscribing to `fuel-core` to receive type `X` events
  - Verifying that type `X` events were received, processed, and indexed
  
Additional Context
- This example could be featured in the "Examples" section of the book when https://github.com/FuelLabs/fuel-indexer/pull/24 is merged

**Comment by mitchmindtree** [comment]
Sounds great, and a nice way to get familiar!
