### ISSUE TITLE
Investigate use of README vars

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#28]
- In the [Getting started](https://github.com/FuelLabs/fuel-indexer/blob/master/docs/src/getting-started/setup.md) section of the Fuel Indexer book, we are using vars such as `OPENSSL_LIB_DIR` and `OPENSSL_INCLUDE_DIR` for installation on Arch Linux
- We'd like to investigate this in order to determine whether or not we actually need these vars
- Documentation should be updated according to whatever conclusion is reached

**Comment by deekerno** [comment]
Closing as it looks like this was completed by way of #77.
