### ISSUE TITLE
Optimize transaction fetching

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#288]
- After https://github.com/FuelLabs/fuel-indexer/pull/279 the indexer will support fetching transactions using a Fuel GQL client
- Currently, the `fuel-indexer::service` fetches transactions individually, iterating over each `TransactionIdFragment` included in a block's transactions (`block.transactions`)
- We should optimize this functionality a bit by only making a single call using the `client.transactions()` (plural) API
- The transactions returned by  a `transactions()` call should be the same transactions that are included in `block.transactions`

**Comment by deekerno** [comment]
I'm currently working on an implementation of a separate endpoint on the client that returns blocks with full transactions included rather than their ID fragments.

**Comment by ra0x3** [comment]
https://github.com/FuelLabs/fuel-core/pull/1175
