### ISSUE TITLE
Create a popular/interesting/easy-to-understand use-case indexing example

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#291]
- We have a few indexer examples, but we need one that is less-techy and able to be easily understood by dApp developers and the broader community
- Ideally we'll have cleaned a few of our hacks/issues up by the time this issue is started

Additional context
- We should actually work with @camiinthisthang on this
- This might have include a frontend

**Comment by camiinthisthang** [comment]
What does pop-sugar indexing mean? @ra0x3
