### ISSUE TITLE
`Identity` wrapper type for `Address` and `ContractId`

### ISSUE THREAD

**Issue by alphak3y** [FuelLabs/fuel-indexer#296]

**Comment by ra0x3** [comment]
@alphak3y Thanks for opening this up 🥳 
- I agree that it's best practice to have as much parity between the Fuel indexer and the rest of Fuel's ecosystem - and implementing `Identity` is a step in that direction
- However, where this gets interesting is when defining an `Identity` type in GraphQL schema
  - While GraphQL [supports enums](https://www.apollographql.com/tutorials/side-quest-intermediate-schema-design/the-enum-type), defining an `Identity` in a Sway/Rust-like way (e.g., `Identity::Address`) is unsupported in GraphQL
    - Further since GraphQL is a core component of the features, we would want to only implement what can be implemented for _all_ components
- Thankfully, at the moment, I believe `Identity` is limited to `Address`, `AssetId`, and `ContractId` (don't quote me)
  - So as a quick workaround you'll just have to be aware which of those types ☝️ you're referring to
- By no means is this a final verdict and happy to hear any advice/recommendations on the best way to implement `Identity` in GraphQL schema

**Comment by ra0x3** [comment]
So I have a PR up for this, but in order to avoid having to wrap types in `fuel_indexer_plugin::types::Identity` we will need https://github.com/FuelLabs/fuels-rs/issues/717
