### ISSUE TITLE
Add `run_once` ability back to `IndexerService`

### ISSUE THREAD

**Issue by deekerno** [FuelLabs/fuel-indexer#383]
In fixing #348, adjustments were made in order to correctly allow for an index to be stopped; one of the changes did away with the need for the "kill switch" `bool`. We were also leveraging this `bool` for the ability to run an index once; however, it wasn't working as intended. We should add it back in the near future. it should also be a part of the index's manifest.

**Comment by ra0x3** [comment]
After giving it some thought I think we can close this. That previous implementation was never tested and never used. So `run_once` might not have even worked in the first place. Users can stop an running index via the functionality @deekerno added - and that should be all we need for now
