### ISSUE TITLE
Swap `fuel_indexer_types::abi::Identity` for `fuels_core::Identity`

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#386]
- With the completion of https://github.com/FuelLabs/fuel-indexer/issues/296 we will have support for `Identity` types
- However, the SDK (at the time) did not readily have an `Identity` type that would work for the Indexer -- and we can't wait for them to support it
- So we created our own `Identity` that does everything the SDK `Identity` does, plus a little more
- This works fine but requires the user to convert `Identity` types from Sway contracts to `Identity` types in indexer modules using `Identity::from(my_event.identity_field)`
- This if fine, but a hack. Ideally we should be using `fuel_core::Identity`

**Comment by ra0x3** [comment]
Blocked by https://github.com/FuelLabs/fuels-rs/issues/717

**Comment by deekerno** [comment]
Blocked by #423.
