### ISSUE TITLE
Querying nested objects only provides IDs of the nested objects

### ISSUE THREAD

**Issue by tkporter** [FuelLabs/fuel-indexer#452]
I'm a total noob when it comes to GraphQL so it's very possible I'm making a dumb mistake here. However, taking the example from the docs here https://fuellabs.github.io/fuel-indexer/master/components/database/foreign-keys.html#implicit-foreign-keys, if I try to query:
```
query {
  library {
    id,
    book {
      id,
      name
    }
  }
}
```

I'm only able to get a response that includes the book's ID, but no name, e.g.:
```
[
  {
    id: "<library id>",
    book: "<book id>",
  }
]
```

When I really would want
```
[
  {
    id: "<library id>",
    book: {
      id: "<book id>",
      name: "<book name>",
  }
]
```

This happens both when I use implicit and explicit foreign keys

**Comment by ra0x3** [comment]
- After taking a look at this today, this isn't so much a bug as it is just not supported functionality
- We need to convert [this TODO](https://github.com/FuelLabs/fuel-indexer/blob/master/packages/fuel-indexer-schema/src/db/graphql.rs#L257) into an issue
  - I'll do this and tag it as an enhancement
- For now the workaround is to use that `<book id>` to make another fetch request to fetch the entire, single `Book`
  - Again, I know this isn't ideal, just a temporary workaround, as implementing arbitrary joins with nested queries via raw GraphQL schema is a non-trivial task, and will take some time to triage properly

**Comment by ra0x3** [comment]
Closing this in favor of https://github.com/FuelLabs/fuel-indexer/issues/460. Feel free to comment there with any questions/concerns. We'll try to get this triaged ASAP.
