### ISSUE TITLE
Update mdbook: Distinguish between "users" and "contributors" in book

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#483]
- The book currently seems targeted toward "contributors"
  - Specifically the "Getting Started" and "Dependencies" sections 
- We should update the book to primarily target "users"
- We should include a separate section in the book (maybe towards the bottom) for "contributors"

**Comment by deekerno** [comment]
`mdbook` allows for additional separators in the document outline, so we can put all "reference" type stuff in a separate _Contributors_ heading.

**Comment by ra0x3** [comment]
@deekerno we basically need to rewrite the book for users (not contributors), and add a special (smaller) section for actual contributors (example: our “getting started” section and dependencies is mostly for contributors, not users)

this is gonna take a bit of time, but we can throw a PR up and all share as co-authors (updating as we go, and fixing things as we read over them)

cc @hrryndrsn

**Comment by ra0x3** [comment]
Closing in favor of the more actionable https://github.com/FuelLabs/fuel-indexer/issues/489
