### ISSUE TITLE
Refactor mdbook

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#489]
- Our book needs to be refactored
- It has been noted that our book is more so targeted towards "Developers" and not "Users"
- To fix this, we should refactor the book to streamline the content, remove unnecessary dev docs, and generally add clarity
- This is a follow up to https://github.com/FuelLabs/fuel-indexer/issues/483
- My recommendations are as follows:

- [ ] Quickstart
  - Refactored in https://github.com/FuelLabs/fuel-indexer/pull/486
- [ ] Getting Started
  - Keep the architecture diagram and update the architecture diagram
    - Show bi-directional communication (maybe use Lucid Charts?)
    - Diagram is 85% there
  - Change "System dependencies" and "application dependencies" to just "Dependencies"
    - Should include fuelup, postgres, docker, sqlite, and wasm-snip
  - [ ] Installing Rust
    - Remove this section
  - [ ] System dependencies
    - Remove this section
  - [ ] Application dependencies
    - Remove this section
      - [ ] Database
        - Remove this section
  - [ ] Add new section `Dependencies`
    - Should include Docker, Postgres, SQLite
    - Should only include `wasm-snip`
  - [ ] Configuration
    - Explain that you can use CLI args/opts OR the config file
    - Make sure the CLI args/opts are up-to-date 
    - Move this from under "Getting started"
  - [ ] A Fuel Indexer Project
    - Only explain the project insofar as the indexer is concerned (not other components, Sway, etc)
    - Move `Manifest`, `Schema`, `Module` from "Components -> Assets" to under "Fuel Indexer Project"
      - I applaud our layout but maybe making things a bit more concise/straight-to-the-point will help
- [ ] Examples
  - Keep these as is
- [ ] Plugins
  - [ ] forc-index
    - Update this with latest commands
    - Make sure to communicate that **the plugin is the primary interface to fuel indexer development**
- [ ] Components
  - [ ] Assets
    - Remove this section (and subsections)
    - [ ] Manifest
      - Remove this (moved to "Fuel Indexer Project")
    - [ ] Schema
      - Remove this (moved to "Fuel Indexer Project")
    - [ ] Module
      - Remove this (moved to "Fuel Indexer Project")
  - [ ] Database
    - Keep this and its subsections as is
  - [ ] GraphQL
    - Keep this and subsections as is
- [ ] What Can I Index?
  - Keep this and subsections as is

@deekerno @hrryndrsn 
- Feel free to chime in here. I will update this 👆 with anything you guys feel I missed or left out. 
- From here, we could put up a PR that we all co-author, and just tick each of these ☝️ boxes as we go.

**Comment by deekerno** [comment]
I generally agree with all of the recommendations listed. 🆗 

Also, if we really want to keep a section for more technical users, perhaps we can have two outline headings: _User Guide_ and _Developer Reference_.
