### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#490]
- So we need to update our project README
- The README is super comprehensive, but maybe a bit verbose, and targeted toward "devs" as opposed to "users" (yes they can be the same thing but let's not be overly pedantic)
  - This devs vs users thing was previously mentioned in https://github.com/FuelLabs/fuel-indexer/issues/483
- https://github.com/FuelLabs/fuel-indexer/issues/466 pointed out a lot of things that aren't super clear

Suggestion:
- Maybe the README format should be:
  - Intro & Outline (we currently have these, obviously the outline would have to be updated to reflect the latest content)
  - We break things down in to a "User" section and a "contributors" section (users section comes first)
  - Users section would basically just be the Quickstart https://github.com/FuelLabs/fuel-indexer/issues/482
  - Contributors section would include (some of which are listed in https://github.com/FuelLabs/fuel-indexer/issues/489):
    - Downloading rust
    - Cloning repository
    - Installing dependencies
    - Running migrations
    - Running the "hello world" example
      - Not going into detail about schema/manifest and all that, but just literally running the example and seeing indexed content)
    - Using docker
      - Maybe include a docker-compose here with fuel-core, postgres, fuel-indexer, and fuel-indexer-api-server

**Comment by ra0x3** [comment]
@deekerno  Feel free to chime in with suggestions

@hrryndrsn You specifically went through the "devs" experience recently, so chime in with thoughts here as well

**Comment by deekerno** [comment]
Yeah, I like our README because it leaves no ambiguity, but for first time users, it should really be focused on getting them from "zero to 'here's a query response'" as quickly and easily as possible. I'm in favor of the changes listed above. 👌🏽

**Comment by ra0x3** [comment]
@deekerno  To be fair I loved that you tackled the README and flushed it out - as prior to your work it was literally just like 3 broken commands 😅 .

**Comment by hrryndrsn** [comment]
I have a lot to say on the subject, however first things first. I think we should decide what content should live in what document first

**Comment by hrryndrsn** [comment]
IMO the readme should be very easy to scan and not have a lot of blocks of text. 

it should contain information about 
- installation
- usage
- configuration 
- how to run the repository locally (which is not the same as building from source)
- how to contribute 
- link to more information and long form Docs 

I think the quick start probably should be moved to the book and not duplicated unless we can just reference the same markdown content somehow

**Comment by hrryndrsn** [comment]
The quickstart is not too long now with #486 so maybe it's not too much to have it in the readme as well for simplicity 

i found the indexer book is also quick hard to find on google

**Comment by hrryndrsn** [comment]
We should also highlight somewhere in the README, we actually publish a docker container you can just run. that's probably one of the simpler ways to get started as a "User".

**Comment by deekerno** [comment]
Closed by our recent documentation PRs.
