### ISSUE TITLE
forc-index: Make --manifest optional and read from default location

### ISSUE THREAD

**Issue by hrryndrsn** [FuelLabs/fuel-indexer#493]
Issue:
`--manifest` is a required argument to `forc-index build`. There is no scenario where you dont pass `--manifest`.
```
$ forc-index build
error: The following required arguments were not provided:
    --manifest <MANIFEST>

USAGE:
    forc-index build [OPTIONS] --manifest <MANIFEST>

For more information try --help
```
Passing `--manifest` to `forc-index is annoying if it is expected to be in the local directory.
```
forc-index build --manifest my_index.manifest.yaml
```
take `cargo` as a example, you do not have to pass `--manifest`
```
cargo build # looks for ./Cargo.toml

cargo build --manifest Cargo.toml # this would be annoying
```

Desired behavior:
1. try read manifest from local dir by default
```
forc-index build
```
2. Optionally pass manifest if you want to override
```
forc-index build --manifest ../path/to/my_other_index.manifest.yaml
```

**Comment by ra0x3** [comment]
- Thanks for this
- I agree, and this has been in the backlog.
- `forc index build` requires that there be a valid cargo manifest in the current directory
- So if you're in the index directory, you should be able to take the dasherized `current-directory-name` (which is the name of the project), and `snake_case` it, and then match it with the index manifest in the current directory

@hrryndrsn This is not a bug. This is functionality working as it was intended, but should be enhanced

**Comment by ra0x3** [comment]
Done in https://github.com/FuelLabs/fuel-indexer/pull/518
