### ISSUE TITLE
`forc-index new` should handle relative paths as well

### ISSUE THREAD

**Issue by harry-anderson** [FuelLabs/fuel-indexer#494]
`forc-index new` generates code with absolute paths to files on the current user's home directory.

```bash
forc-index new my_index
```
`src/lib.rs`
```rust
extern crate alloc;
use fuel_indexer_macros::indexer;
use fuel_indexer_plugin::prelude::*;

#[indexer(manifest = "/home/harry/dev/test/quick_start_compose/indexer/my_index/my_index.manifest.yaml")]
pub mod my_index_index_mod {

    fn my_index_handler(block_data: BlockData) {
        Logger::info("Processing a block. (>'.')>");

        let block_id = first8_bytes_to_u64(block_data.id);
        let block = Block{ id: block_id, height: block_data.height };
        block.save();

        for transaction in block_data.transactions.iter() {
            Logger::info("Handling a transaction (>'.')>");

            let tx = Tx{ id: first8_bytes_to_u64(transaction.id), block: block_id };
            tx.save();
        }
    }
}
```
Notice this line 
```
#[indexer(manifest = "/home/harry/dev/test/quick_start_compose/indexer/my_index/my_index.manifest.yaml")]
```
if I commit this code and someone else then clones it, the manifest file path will be incorrect on their local machine unless they have the exact username and home directory structure as me.
```
harry@xps:~/dev/test/quick_start_compose/indexer/my_index$ forc-index build --manifest my_index.manifest.yaml ▹▹▹▸▹ ⏰ Building...                                                                                                                                                                                                    Compiling my_index v0.0.0 (/home/harry/dev/test/quick_start_compose/indexer/my_index)
▹▹▹▹▸ ⏰ Building...                                                                                                                                                                                                 error: custom attribute panicked
 --> src/lib.rs:5:1
  |
5 | #[indexer(manifest = "/home/not_harry/dev/test/quick_start_compose/indexer/my_index/my_index.manifest.yaml")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: Could not parse manifest.: FileError(Os { code: 2, kind: NotFound, message: "No such file or directory" })

warning: unused import: `fuel_indexer_plugin::prelude::*`
 --> src/lib.rs:3:5
  |
3 | use fuel_indexer_plugin::prelude::*;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default
```

Can we make the code gen reference the local manifest using relative paths or [cargo env vars ](https://doc.rust-lang.org/cargo/reference/environment-variables.html)?

**Comment by ra0x3** [comment]
@hrryndrsn 
- So this gets back to what I was saying earlier and also kinda ties into https://github.com/FuelLabs/fuel-indexer/issues/495
- The plugin is not for _contributors_, the plugin is for _users_
  - Not all users will be contributors, while most contributors (almost by definition) will somewhat be users
  - The users of `forc index` won't even have the fuel-indexer repository on their machine
- At no time should someone create an index via `forc index new` and try to check that in
  - Remember we're making a big docs push to distinguish "users" and "contributors"
- Now (again this relates to https://github.com/FuelLabs/fuel-indexer/issues/495) should we add a flag to the plugin (most if not all commands) to let the user specify whether they want absolute or relative paths? 
  - Yes, I think things are pointing in that direction
  - I planned to wait to discuss this but the golden nugget of insight in https://github.com/FuelLabs/fuel-indexer/issues/495 isn't "remove examples from the workspace". Rather, it's "Hey, absolute paths are cool! But if I want to use relative paths (for whatever reason) you should allow me that functionality"


Hope this helps a bit

**Comment by hrryndrsn** [comment]
if i use create react app, i can commit the output with no changes. same for cargo, why is this different @ra0x3 ?
