### ISSUE TITLE
Remove examples/ from workspace

### ISSUE THREAD

**Issue by hrryndrsn** [FuelLabs/fuel-indexer#495]
Examples should NOT be in the workspace :fearful: because it means they cannot be built independently 

[Cargo.toml](https://github.com/FuelLabs/fuel-indexer/blob/master/Cargo.toml)
```
[workspace]
# Use the new resolver to prevent dev-deps and build-deps from enabling debugging or test features in production.
resolver = "2"
members = [
   "examples/block-explorer/explorer-index",
   "examples/hello-world-native/hello-index-native",
   "examples/hello-world/hello-bin",
   "examples/hello-world/hello-index",
```
It means you cannot clone the examples and build them
```
harry@xps:~/dev/github/fuel-indexer/examples/hello-world/hello-index$ forc-index build --manifest ../hello_index.manifest.yaml 
▹▹▹▸▹ ⏰ Building...                                                                                          Finished dev [unoptimized + debuginfo] target(s) in 0.15s
▪▪▪▪▪ ✅ Build succeeded.                                                                                 error: failed to read file /home/harry/dev/github/fuel-indexer/examples/hello-world/hello-index/target/wasm32-unknown-unknown/debug/hello-index.wasm
  caused by No such file or directory (os error 2)
```
It is a very common pattern to have examples in a [rust crate](https://github.com/wasmerio/wasmer) that build independently, for introduction purposes
```
git clone https://github.com/wasmerio/wasmer
cd wasmer/examples/
cargo run --example hello-world --release --features "cranelift"

>  Finished release [optimized] target(s) in 1m 23s
     Running `/home/harry/dev/github/wasmer/target/release/examples/hello-world`
Hello, world!
``` 
if you exclude the examples from the workspace, you can still build the them and use their build artefacts from the example `target` directory (because our examples are themselves cargo projects):
```
$ cargo build --release --target wasm32-unknown-unknown
    Finished release [optimized] target(s) in 1.20s
$ ls
Cargo.lock  Cargo.toml  my_index.manifest.yaml  schema  src  target
```

**Comment by hrryndrsn** [comment]
also see http://xion.io/post/code/rust-examples.html

**Comment by hrryndrsn** [comment]
I had a look at the [Sway](https://github.com/FuelLabs/sway/blob/master/Cargo.toml) cargo workspace and they have also excluded the examples:
```
exclude = [
    "examples/*"
]
```

**Comment by hrryndrsn** [comment]
also see [sway example checker](https://github.com/FuelLabs/sway/tree/master/scripts/examples-checker)

**Comment by hrryndrsn** [comment]
please if you could elaborate @ra0x3 

and please also don't close it yet

**Comment by hrryndrsn** [comment]
see https://github.com/yewstack/yew/tree/master/examples

**Comment by hrryndrsn** [comment]
> When you’re writing a library for other programs to depend on, it is paramount to think how the developers are going to use it in their code.

> The best way to ensure they have a pleasant experience is to put yourself in their shoes. Forget the internal details of your package, and consider only its outward interface. Then, come up with a realistic use case and just implement it.

> In other words, you should create complete, end-to-end, and (somewhat) usable example applications.

http://xion.io/post/code/rust-examples.html

**Comment by deekerno** [comment]
Great job on including additional examples to illustrate the issue; that really helps a lot. I've always worked a bit differently when I look at crate examples, so I actually had no idea that things were structured this way (TIL!).

**Comment by ra0x3** [comment]
We can discuss this during team meeting Monday

**Comment by hrryndrsn** [comment]
@ra0x3 in the spirit of async comms! 

If you have concerns, please list your concerns here
