### ISSUE TITLE
Dockerize our examples

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#499]
- It has been noted that running examples requires several commands
- Example (to run the `hello-world` example)
```bash
# from project root
cd fuel-indexer/

# start a fuel-node and deploy contract
cargo run --bin fuel-node

# start the service
cargo run --bin fuel-indexer -- --manifest examples/hello-world/hello_index.manifest.yaml

# trigger some data
cargo run --bin hello-world
```
- This could be streamlined a bit using Docker to the point where the result is:

```bash
docker run ghcr.io/fuellabs/fuel-indexer:hello-world --pull=always
```
- This would be implemented for the `hello-world-native` and `block-explorer` examples as well

Additional context
- This might be a great chance to go ahead and dockerize our `fuel-node` test binary
  - We use this binary to quickly spin up a fuel-node with a wallet that has coins (so that we can go ahead and transact) 
  - Further, with a dockerized `fuel-node`, we wouldn't need to build the `fuel-node` on CI anymore! 🙌 
- We can discuss maybe what the image name is called

**Comment by hrryndrsn** [comment]
i was trying something like this here https://github.com/hrryndrsn/fuel_indexer_docker_quick_start
