### ISSUE TITLE
Add comments to index manifest generated by `forc-index new `

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#510]
- `forc index new` generates a manifest with some default parameters ([here](https://github.com/FuelLabs/fuel-indexer/blob/master/plugins/forc-index/src/utils/defaults.rs#L60))
- We should add some helpful comments for these default parameters which might be useful to new users

Additional context
- Maybe something like below, where the comments/descriptions are copied [from our book](https://fuellabs.github.io/fuel-indexer/master/components/assets/manifest.html)

```yaml
# ...

# The particular start block after which you'd like your indexer to start indexing events.
start_block: ~

# The contract_id specifies which particular contract you would like your index to subscribe to.
contract_id: ~

# ...

**Comment by yash251** [comment]
please assign me this issue

**Comment by ra0x3** [comment]
Hi @yash251 you don't have to wait to be assigned, feel free to put up a PR if you feel comfortable 😄  

(Being "assigned" is more so for internal Fuel contributors. External contributors don't have to follow those exact rules 👌 )

**Comment by deekerno** [comment]
Just like @ra0x3 said, you don't have to be assigned through GitHub, but thanks for letting us know that you want to work on this issue! We'll make sure that no internal Fuel contributors work on this while you're working on it.

**Comment by yash251** [comment]
@ra0x3 @deekerno I have added the comments along with the indentation. Let me know if I need to change anything

```rust
pub fn default_index_manifest(
    namespace: &str,
    index_name: &str,
    project_path: &str,
) -> String {
    format!(
        r#"
            # A namespace is a logical grouping of declared names. Think of the namespace as an organization identifier
            namespace: {namespace}
        
            # The identifier field is used to identify the given index.
            identifier: {index_name}
        
            # The abi option is used to provide a link to the Sway JSON ABI that is generated when you build your project.
            abi: ~
        
            # The particular start block after which you'd like your indexer to start indexing events.
            start_block: ~
        
            # The contract_id specifies which particular contract you would like your index to subscribe to.
            contract_id: ~
        
            # The graphql_schema field contains the file path that points to the GraphQL schema for the given index.
            graphql_schema: {project_path}/schema/{index_name}.schema.graphql
        
            # The module field contains a file path that points to code that will be run as an executor inside of the indexer.
            # Important: At this time, wasm is the preferred method of execution.
            module:
              wasm: ~
        
            # The report_metrics field contains boolean whether or not to report Prometheus metrics to the Fuel backend
            report_metrics: true
        "#
    )
}
```

**Comment by ra0x3** [comment]
Looks good @yash251 feel free to throw this in a PR and we'll review :)
