### ISSUE TITLE
`forc index check` does not display ⛔️ for missing components

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/fuel-indexer#512]
When running `forc index check` and there are missing components the status still displays the ✅. This is problematic as I briefly checked the status to match what was in the README before continuing on to the next step. The result was a number of errors.

For example, this was the output of when I ran `forc index check` for the first time:
![missing_components](https://user-images.githubusercontent.com/54727135/214523639-f942d84e-3e81-44d7-9e06-233e64adee2b.png)

Although `psql`, `sqlite`, and `wasm-snip` are missing there is still the ✅.

I would also include the commands to install these to make the step-by-step setup process more idiot-proof.

**Comment by ra0x3** [comment]
Ah, thanks @bitzoic should be a pretty easy fix.
