### ISSUE TITLE
Add the `forc-index` plugin to CI

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#517]
- Users are using the `forc index` plugin increasingly more often
- We're discovering instances of breakage
  - E.g., An internal Fuel contributor found that the schema for the indexer did not match the Quickstart
- We should add CI to ensure we catch these things before merging PRs

Additional context
- We could add a job that runs `forc index new` and `forc index build`
  - `forc index deploy` would be more complicated, but we could add this down the road

**Comment by ra0x3** [comment]
@deekerno 
- Just FYI tagging this as high priority now. 
- Whilst troubleshooting a user error, I think I'm noticing some plugin breakage

**Comment by deekerno** [comment]
Noted, switching gears to complete this.
