### ISSUE TITLE
Make SQLite work with `namespace` functionality

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#540]
- When using the Indexer with Postgres, a table is identified using `$namespace.$type_name`
 - Where `$namespace` is the namespace specified in the indexer manifest, and `$type_name` is the type name of the GraphQL type
 - This `$namespace` is used to create a public Postgres schema, under which all the `$type_name`s are listed
- This works fine for Postgres, but doesn't work for SQLite because SQLite does not use schema functionality
  - With SQLite, all tables are stored in a flat namespace
- We should update our SQLite implementation to use psuedo-namespaces as well
- The idea is that we will just prefix `$namespace` to every SQLite table name, in order to create a psuedo-namespace
  - So an indexer with namespace `foo` and GraphQL type `bar` would be referred to as `foo.bar` in Postgres, and `foo_bar` in SQLite
- This would allow us to keep a more decent level of parity between the two backends

Additional context
- This might require a SQLite (only) migration

**Comment by deekerno** [comment]
Obsoleted by #547.
