### ISSUE TITLE
 Error during pull fuel-indexer: no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by chlenc** [FuelLabs/fuel-indexer#543]
Hey guys.
When I try to pull the indexer on my computer using this tutorial
https://fuellabs.github.io/fuel-indexer/master/quickstart/index.html

I have this error
```
^^/p/fuel >>> docker pull ghcr.io/fuellabs/fuel-indexer:latest                                                                                                                                          (130) 11:03:28 

latest: Pulling from fuellabs/fuel-indexer
no matching manifest for linux/arm64/v8 in the manifest list entries
```
(I have MacBook with m1)

**Comment by chlenc** [comment]
https://forum.fuel.network/t/error-during-pull-fuel-indexer-no-matching-manifest-for-linux-arm64-v8-in-the-manifest-list-entries/1711

**Comment by ra0x3** [comment]
We have M1 builds now! 🥳

**Comment by chlenc** [comment]
Thanks guys 
Super appreciated
