### ISSUE TITLE
Add "resume indexer" functionality

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#568]
- As an indexer executor runs, it keeps track of block height during every call to `handle_events`
  - [Here](https://github.com/FuelLabs/fuel-indexer/blob/master/packages/fuel-indexer-macros/src/indexer.rs#L637)
- This allows the user to stop a running indexer, and sort've keep track of where their indexer last stopped
- We also allow users to set a `start_block` in their indexer manifest - where this `start_block` determines at which block height the user's indexer will start indexing 
  - [Here](https://github.com/FuelLabs/fuel-indexer/blob/master/packages/fuel-indexer/src/executor.rs#L81)
- However, there's currently no way for an indexer to "pick up where it left off" automatically
- We should add functionality that allows an indexer to "pick up where it left off" by using the `IndexMetadata`
- When the indexer is created, it would either start at `start_block` or `pick_up_where_you_left_off_block`, depending on what is specified in the indexer manifest
  - Maybe `pick_up_where_you_left_off_block` should take precedence over `start_block`?

Additional context
- This might require some new parameter/flag in the indexer manifest

**Comment by deekerno** [comment]
@ra0x3

It sounds like the implementation could be as follows:
- Add a `resumeable` flag in the manifest
- If `resumeable == true`, then check if the last processed block is greater than `start_block`, and retrieve and process blocks until the head of the chain is reached; the index would then start indexing current blocks as they come in.
- If `resumable != true`, then the index defaults to the current behavior of checking the start block and indexing once it is reached; there would be no data from the time that the index was "off" unless an operator points the indexer service to a node that is syncing and sending the missing blocks from the client.

Thoughts?

**Comment by ra0x3** [comment]
@deekerno
- Seems correct
- I think we would need to decide whether or not we want to allow `start_block` _and_ `resume`
  - `resume` sort've supersedes `start_block` since `resume` is just  another form of `start_block` 🤔 
  - Maybe if both are included we can prefer `resume`?

Thoughts @rvmelkonian

**Comment by rvmelkonian** [comment]
I'm trying to think of a usecase where someone would want their indexer to not be resumable, but I can't think of one. Would it make sense to make all indexers resuable by default? Similar to how when you run a blockchain node, you just expect it catch up to latest the block. 

Apart from a user exiting the process, or any other unexepcted failure, would there be any other reason why an indexer would pause / get out of sync? I guess I'm wondering if we want the indexer to be `pausable` aswell as `resumable`. Perhaps this is out of scope.

If a `start_block` is not defined (how the indexers are now), the indexer always starts indexing from the fuel genesis block?

**Comment by ra0x3** [comment]
@rvmelkonian 

> I'm trying to think of a usecase where someone would want their indexer to not be resumable, but I can't think of one
- Resuming means you care about _every_ block, in order, sequentially
- While I also see that as a common case, I don't see that as the default case
  - Example: I stop my indexer and don't want to wait for it to pick back up (aka resume)
    - I might be writing a test indexer
    - I might be only interested in seeing my index have the _latest_ data
      - Again, especially for testing/debugging purposes here
 - I would say in most cases for me personally, I don't care about my indexer being "resumable" -- because I do a lot of testing (as do most ppl who use the service right now)
   - But again, yes, any production-level dApp is gonna probably always use resumability (not a word)

> Apart from a user exiting the process, or any other unexepcted failure, would there be any other reason why an indexer would pause / get out of sync
- If the indexer got out of sync it would be due to user input (e.g., `Ctrl+C` or `forc index remove`), or some technical error.

> I guess I'm wondering if we want the indexer to be pausable aswell as resumable. Perhaps this is out of scope
- Pause-able would be super interesting. But I agree with you that this functionality might be a separate issue/PR

> If a start_block is not defined (how the indexers are now), the indexer always starts indexing from the fuel genesis block?
- Si
