### ISSUE TITLE
Add cross build Docker M1 support

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#578]
- Initial issue is https://github.com/FuelLabs/fuel-indexer/issues/543
- We need to add Docker M1 support as it's becoming a hot topic
- Doesn't look like any project at Fuel currently has M1 Docker support so this might be a first
- Ideally a user on ARM should be able to run all the Docker commands the same as a user on Intel (for example)

Additional context
- Will probably require docs updates?

**Comment by ra0x3** [comment]
CC @Voxelot @tirkesi (copying over the Slack context to here)


Brandon Kite
  [16 hours ago](https://fuellabs.slack.com/archives/C01L1HUJSL8/p1676328763683529?thread_ts=1676314822.690369&cid=C01L1HUJSL8)
Since Rust supports targeting alternate architectures (e.g. you can build for arm on an x86 without emulation), maybe we could split the build phase to run on whatever the native arch of the docker host is and then only make the [second stage](https://github.com/FuelLabs/fuel-core/blob/master/deployment/Dockerfile#L31) use the QEMU env?
[Dockerfile](https://github.com/FuelLabs/fuel-core/blob/master/deployment/Dockerfile)


Brandon Kite
  [16 hours ago](https://fuellabs.slack.com/archives/C01L1HUJSL8/p1676329013653409?thread_ts=1676314822.690369&cid=C01L1HUJSL8)
Finally, depending on your project, the language that you use may have good support for cross-compilation. In that case, multi-stage builds in Dockerfiles can be effectively used to build binaries for the platform specified with --platform using the native architecture of the build node. A list of build arguments like BUILDPLATFORM and TARGETPLATFORM is available automatically inside your Dockerfile and can be leveraged by the processes running as part of your build.
https://docs.docker.com/build/building/multi-platform/ (edited)


Brandon Kite
  [16 hours ago](https://fuellabs.slack.com/archives/C01L1HUJSL8/p1676329154033479?thread_ts=1676314822.690369&cid=C01L1HUJSL8)
so we'd basically need to check the TARGETPLATFORM arg and convert that into a --target arg on the cargo build commands (edited)

**Comment by FossilFrank** [comment]
Any update on this?

We've been holding of on our indexer work to see if it would become possible to build this on Macs

**Comment by ra0x3** [comment]
@FossilFrank 

You can build/run docker fine on M1 (and have been able to for weeks), there’s nothing blocking on that. 

This issue is regarding cross build support of M1 (which we don’t currently have). Admittedly the title is a bit of a misnomer. 

But yea just docker build the deployment/Dockerfile for your platform and should work

**Comment by Voxelot** [comment]
Here's some good info on this from the creator of buildx: https://github.com/tonistiigi/xx#rust
