### ISSUE TITLE
Spruce up docs

### ISSUE THREAD

**Issue by rvmelkonian** [FuelLabs/fuel-indexer#582]
### Dependencies
- [x] Add fuel-core. A node is needed to be running in order to run the example in 3. Hello World. It's also generally needed for dev, the indexer outputs errors when it's not running. 

### Quickstart 
- [x] all `forc index` commands yield `error: Found argument 'index' which wasn't expected, or isn't valid in this context`. Update to `forc-index`
- [ ] Querying yields an empty array. 
  - After deploying `hello_index.manifest.yaml` and running:
  
```bash
curl -X POST http://0.0.0.0:29987/api/graph/my_project/hello_index \
   -H 'content-type: application/json' \
   -d '{"query": "query { tx { id hash block }}", "params": "b"}' \
| json_pp
```

It returns : `[]` Perhaps this is expected for now, if so we should update the docs to reflect this. 

### Hello World
- [x] update the doc comment `cargo build -p hello-index --release --target wasm32-unknown-unknown` to `cargo build -p hello_index --release --target wasm32-unknown-unknown` (underscore, not hyphen).
- [x] update the doc comment ` cargo run --bin fuel-node` to `cargo run --bin fuel-nod -- run`.
- [ ] update the path in doc comment `cargo run --bin fuel-indexer -- --manifest examples/hello-world/hello_index.manifest.yaml` to examples/hello-world/hello-index/hello_index.manifest.yaml`
- [ ] However even with the correct path, this command yields the error:
```
Found argument '--manifest' which wasn't expected, or isn't valid in this context
```
which seems strange as it exists inside `IndexerArgs`. I tried:
`forc-index deploy --manifest examples/hello-world/hello_index/hello_index.manifest.yaml` But that always gives the error
```
Error: missing field `package` at line 28 column 1
```
This error happens no matter what manifest file I try to deploy with `forc-index`

- [x] General thing is that the HelloWorld file in the doc doesn't match what exists in our `examples/` directory. Do we want them to match?

### Block Explorer
- [x] update the doc comment `cargo build -p explorer-index --release --target wasm32-unknown-unknown` to `cargo build -p explorer_index --release --target wasm32-unknown-unknown` (underscore, not hyphen).
- [ ] update the doc comment ` bash scripts/utils/start_test_components.bash`, yields no such file or directory. Anyone have this script handy, do we want it still?
- [ ] cargo run --bin fuel-indexer -- --manifest examples/block-explorer/manifest.yaml yields the same error: 
```
Found argument '--manifest' which wasn't expected, or isn't valid in this context
```

@ra0x3 @deekerno I'll tick off the items I can action now, any unticked items I need some clarification before going forward. 

### Note
- Should we swap put the HelloWorld example in the docs with the two hello world we have in the repo, native and non native?

**Comment by ra0x3** [comment]
@rvmelkonian Just a comment on `forc-index` vs `forc index`
- Users will always use `forc index`
- We will _mostly_ use `forc index`
- The only reason anyone would use `forc-index` over `forc index` is if you're testing a PR and you clobber `fuelup` by copying the `forc-index` binary over to fuelup's `bin`.

**Comment by rvmelkonian** [comment]
Docs have been updated a lot since this issue. Closing as stale.
