### ISSUE TITLE
Pass --locked flag to commands using manifest

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#64]
- Relates to https://github.com/FuelLabs/fuel-indexer/pull/61
  - Similar to https://github.com/FuelLabs/sway/pull/1951 in sway
- We want the lockfile to be up-to-date when using `cargo build` or `cargo test` (or any command that references manifest dependencies)
- This should happen on CI (possibly locally as well)

Additional context
- [Pass the `--locked` flag to cargo](https://doc.rust-lang.org/cargo/commands/cargo-generate-lockfile.html)

**Comment by mitchmindtree** [comment]
This is addressed in #31

**Comment by ra0x3** [comment]
@mitchmindtree
- I left a note in the review
- I noticed `--locked` was passed for in `cargo check` but not `cargo test` or `cargo test`

Btw if we're only passing `--locked` to `check` because we only want to validate the manifest one time, at the beginning of CI, that's fine. Just wanted to make sure
