### ISSUE TITLE
create Escrow example indexer

### ISSUE THREAD

**Issue by rvmelkonian** [FuelLabs/fuel-indexer#647]
After looking through this repo https://github.com/FuelLabs/sway-applications and @Braqzen talking me through the code, I thought it would be good to integrate one of these applications into our `/examples` to bring parity up between the fuel repos and to continue to build up our examples.

- bring in the Escrow contract and dependencies [https://github.com/FuelLabs/sway-applications/tree/master/escrow]()
- create an indexer for the escrow contract. 
- deploy to testnet and test before submitting the PR  

thoughts @ra0x3 @deekerno

**Comment by ra0x3** [comment]
Would love to get any example functionality with an actual app that we can.

**Comment by rvmelkonian** [comment]
There's no UI, but we can use the tests to guide us @Braqzen

**Comment by rvmelkonian** [comment]
Yeah, we can use the tests [here](https://github.com/FuelLabs/sway-applications/tree/master/escrow/project/contracts/escrow-contract/tests/functions/core).
