### ISSUE TITLE
`forc index deploy` doesn't seem to work with `debug` builds

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#684]
- Title says it all
- `release` builds seem to work fine (and are the preferred way of building)
- We should either fix this and/or make `--release` builds the default - not opt-in (maybe opt-out?)

CC @deekerno and @rvmelkonian for thoughts *pepe-thinks*

**Comment by deekerno** [comment]
Do we have any logs that point us to the cause of the issue?

In any case, for `forc index deploy`, I can't imagine that deploying debug WASM builds has much of a use at all as WASM is already a black box as it is and the only reason to use debug builds is to...debug using informative tools. 🤷🏽‍♂️ So I'm down with making release builds the default with a flag allowing users to choose differently.

**Comment by deekerno** [comment]
Hmm, I think they have a place for the native modules perhaps (if there's a way to inspect the debug information on those builds). I don't know that we should remove the ability for debug builds just in case someone has the knowledge and curiosity to investigate. I'm good with swapping the two for now and making `--debug` a flag to create such builds.

**Comment by ra0x3** [comment]
Closing as this is addressed in https://github.com/FuelLabs/fuel-indexer/issues/712
