### ISSUE TITLE
Subscribe to multiple contracts in the manifest file

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuel-indexer#697]
The manifest file contains a field `contract_id` which is used to subscribe to a contract.
You may specify an id or leave it blank to listen to everything on the network.

It would be nice to subscribe to multiple contracts at once.

The contract id file may take the form of a vector e.g.

```sh
contract_id: [ "0x00..00", "0x00..01" ]
```

**Comment by ra0x3** [comment]
- I think this one is pretty straightforward and read for work @rvmelkonian @deekerno 
- Would also require updates to `manifest` part of the mdbook

**Comment by ra0x3** [comment]
@rvmelkonian 
- While you're in there on this one, might not be a bad idea to allow these `contract_id` parameters to be both namespace (e.g.,, `fuel...`) and non-amespaced (e.g., `0x...`). 
  - I believe we already support the namespaced version. 
- It's something that's been meaning to be done, as we don't currently specify that we _don't_ support non-namespaced addresses
