### ISSUE TITLE
Schema support for values that are required `!` but are an `Option` with a valid `None` value

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuel-indexer#698]
The schema may take a value that is either optional or required (uses the `!`).

Optional values do not persist and required values persist on disk.
The issue is that a required value may be an `Option` type which has a valid `None` value.
Currently, the required values need to be wrapped in `Some(...)` which may be an issue.

Additional support may be required in order to have persistent data for the `Option` type.

For a more general explanation, contracts may want to log values that are `Option` types for which both the `Some(...)` and `None` values are legitimate and both of those should persist.

**Comment by ra0x3** [comment]
@Braqzen Could you elaborate a bit?

- So our `Option` support is only with regard to GraphQL schema (the database layer) - not Sway stuff.
- As you mentioned, when the value is `Some(..)` we persist, and when the value is `None`, we don't
- Are you suggesting we should change that? Wanna make sure I'm understanding correctly

**Comment by Braqzen** [comment]
> @Braqzen Could you elaborate a bit?
> 
> * So our `Option` support is only with regard to GraphQL schema (the database layer) - not Sway stuff.
> * As you mentioned, when the value is `Some(..)` we persist, and when the value is `None`, we don't
> * Are you suggesting we should change that? Wanna make sure I'm understanding correctly

The apps repo has a tendency to set initial values to `None` in storage and then they tend to always have a value `Some(...)` ; however, sometimes a valid value may also be `None`. We may log these at times and would like all values to persist, including the `None` as that may be a valid value like revoking ownership.

My understanding is that if we log an option `None` then it will not persist because it needs to be wrapped in `Some()`.

**Comment by ra0x3** [comment]
We support this now.
