### ISSUE TITLE
Simplify the `Hello World` example in the book

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuel-indexer#699]
To prevent a name collision the schema renames the structs in the Sway code to be `Greeter` and `Salutations` with a comment explaining the collision.
Moreover, it tags on additional values that are not included in the log itself.

When reading the example it would be easier to see what is going on with a 1-to-1 match i.e. no additional values for timestamps / block height etc so that we can see exactly how the log is translated directly into the schema.

Moreover, instead of renaming the schema types completely it would be easier to match on them by using the exact same name as in the Sway code but to prevent a namespace collision a prefix / postfix can be added to the schema type.
The comments may remain to explain the collision.
This would make it easier to spot the Sway->Schema type conversion.

**Comment by ra0x3** [comment]
I agree with the premise that it would be great to not have to worry about name collisions as the indexer author. We should namespace Sway types behind something so that you can re-reference those same names in GraphQL schema.
