### ISSUE TITLE
Auto-update `forc-index` documentation

### ISSUE THREAD

**Issue by 0xmovses** [FuelLabs/fuel-indexer#737]
Related to [this](https://github.com/FuelLabs/fuel-indexer/pull/732#discussion_r1158772442) comment, we should be able to auto update our docs based on the output of `forc-index build --help` and all other forc-index subcommands.

**Comment by ra0x3** [comment]
@rvmelkonian @deekerno 

Off the top of my head I'm thinking:
- We have set of commands `init`, `new`, `build`, `deploy`, etc
- Those commands all have a `--help`
- That `--help` prints to stdout
- These command markdown files (e.g., `build.md`) are just copy/paste of the `--help` output
- We could potentially just run these commands with `--help` then just copy over the output (automagically w/ bash)
- The CI job to check this could run that same command/script on CI then comapare the output to see if it's up to date

Thoughts?
