### ISSUE TITLE
Pull remote contract ABI

### ISSUE THREAD

**Issue by rvmelkonian** [FuelLabs/fuel-indexer#749]

**Comment by ra0x3** [comment]
Will add some context here:

- Regardless of which way (mentioned below) we go about this, we'll need a new plugin command for this
- The _proper_ way to do this would be to download the contract ABI asset from the `forc` package registry
  - https://github.com/FuelLabs/sway/issues/3926
- However, until that is up and stable, something simple like just downloading for a given endpoint might be ok
  - Assuming that the dev using this functionality is aware that they're trusting the source at the URI
  - If someone uses this "arbitrary" download functionality, might help to make them past a `--trust` flag or have some type of `"You are downloading an arbitrary file, you sure you want to do this?" y/N` type of message
- User should be able to provide a destination path to which the file will be downloaded
  - However if a path isn't specified we should try to download to file to a place [according to indexer project structure](https://fuellabs.github.io/fuel-indexer/master/reference-guide/components/fuel-indexer-project.html#as-part-of-a-fuel-project)
- This will also require updates/docs in the book

Extras
- Possibly downloading more than just the ABI
