### ISSUE TITLE
Change paginated API query metadata to only be included in response if requested

### ISSUE THREAD

**Issue by deekerno** [FuelLabs/fuel-indexer#791]
As part of the paginated query support implemented in #763, we automatically return a `PageInfo` object if a user sends a limit in their query. We should change the behavior to return the `PageInfo` object _only_ if it is requested.

edit: Here's additional info.

During a sync with a member of the frontend team, they gave an example of a query that they would typically use:
```
query {
  transactions(first:10) {
    nodes {
      id
    }
    pageInfo {
      hasPreviousPage
    }
  }
  blocks(first:10) {
    nodes {
      id
    }
    pageInfo {
      hasPreviousPage
    }
  }
}
```

As you can see, this query specifically requests for the `PageInfo` metadata object to be returned. Upon clarification, they said that the front-end team would rather the `PageInfo` object only be returned if requested instead of how I originally implemented it (the current behavior is to return it for all paginated queries and it's unable to be specifically requested).

**Comment by ra0x3** [comment]
@deekerno This seems simple enough for me to handle if you prefer (also happy to let you have it if you have a certain way you'd like to see it implemented).

**Comment by deekerno** [comment]
Go for it! You should be able to look for the `PageInfo` object inside of `Operation.parse(...)` and then go from there. 👌🏽
