### ISSUE TITLE
Move to more idiomatic GraphQL API query and response structure

### ISSUE THREAD

**Issue by deekerno** [FuelLabs/fuel-indexer#794]
Our GraphQL API responses are pretty good right now, but as we move to being used by the public, we should try to adhere to common practices or idioms where we can.

The following query is from @luizstacio, and contains what I feel should be a good starting query and response structure:

```
query {
  transactions(first:10) {
    nodes {
      id
    }
    pageInfo {
      hasPreviousPage
    }
  }
  blocks(first:10) {
    nodes {
      id
    }
    pageInfo {
      hasPreviousPage
    }
  }
}
```

The requisite sub-issues are:
- [ ] #791
- [ ] #792
- [ ] #793

**Comment by ra0x3** [comment]
Gonna close.

- Things we're gonna implement tracked in https://github.com/FuelLabs/fuel-indexer/issues/937
- Things we're aware of but not gonna implement at this time tracked in https://github.com/FuelLabs/fuel-indexer/issues/935
