### ISSUE TITLE
Define a TransactionStatus in the schema

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuel-indexer#799]
I have a custom type in the schema which has a field that is the [`TransactionStatus`](https://fuellabs.github.io/fuel-indexer/master/reference-guide/indexing/blocks-and-transactions.html?highlight=enum#transactionstatus).
I cannot define a new type to represent that in the schema because

1) The name collides
2) If I use a different name I get a type mismatch from the actual Rust Enum

How is this type meant to be defined in the schema?

**Comment by rvmelkonian** [comment]
@Braqzen can you include the error message you received and your schema and handler function. Thanks!

**Comment by Braqzen** [comment]
> @Braqzen can you include the error message you received and your schema and handler function. Thanks!

I've deleted that code a while ago now so here are some screenshots from the time
![1](https://user-images.githubusercontent.com/103777923/234263373-4d2263b1-ffd0-4551-8462-b8a7ce87dd9b.png)
![1 (1)](https://user-images.githubusercontent.com/103777923/234263425-b00c1af4-8490-4bfb-82a8-ef6c91345c30.png)
![1 (2)](https://user-images.githubusercontent.com/103777923/234263523-85985255-3a28-403a-a084-8d90ea6c8b84.png)

**Comment by ra0x3** [comment]
I sent this in a Slack message but will also mention it here.

```graphql
type Block {
  id: ID!
}

type FailureStatus {
  id: ID!
  block: Block!
  reason: Charfield!
}

type SqueezedOut {
  id: ID!
  reason: Charfield!
}

type Submitted {
  id: ID!
  time: UInt8!
}

type TxStatus {
  failure_status: FailureStatus
  squeezed_out: SqueezedOut
  submitted: Submitted
}
```

**Comment by ra0x3** [comment]
Closing this as this has been done
