### ISSUE TITLE
Invalid link to the `docker-compose.yaml` file

### ISSUE THREAD

**Issue by rimbi** [FuelLabs/fuel-indexer#807]
[getting-started](https://github.com/FuelLabs/fuel-indexer/tree/master/docs/src/getting-started)/[dependencies](https://github.com/FuelLabs/fuel-indexer/tree/master/docs/src/getting-started/dependencies) has an invlaid link to the `docker-compse.yaml` file.

**Comment by deekerno** [comment]
This looks like it's been fixed. Thanks for reporting this!
