### ISSUE TITLE
`forc index deploy` fails locally, consistently

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#816]
- `forc index deploy` is failing when used locally, consistently 
- This seems to be happening on the unhappy path, where the user tries to deploy to an indexer service behind authentication, without authenticating
- The user should receive a simple `"Unauthorized" - 401"` JSON response, but the reading the response fails
-  The fix from https://github.com/FuelLabs/fuel-indexer/pull/751 does not seem to have been the fix :(
- IMPORTANT: I don't see this happening in prod when using the playground - I just see it locally
  - Also noticing this doesn't happen when authenticating against `cargo run --bin fuel-indexer` -- just seems to happen with the `fuel-indexer` binary directly

Confirming this is not a production issue:
```bash
forc index deploy --path examples/hello-world/hello-indexer --target-dir /Users/rashad/dev/repos/fuel-indexer --url https://beta-3-indexer.fuel.network
```

- Steps to reproduce
  - Start a `fuel-indexer` service using the binary directly 

```
fuel-indexer -- run --embedded-database --run-migrations --fuel-node-host beta-3.fuel.network --fuel-node-port 80 --auth-enabled --auth-strategy jwt --jwt-secret foobar12345 --jwt-issuer FuelLabs
```
  - Try to deploy `forc index deploy` an indexer
  - You should see the error

Additional context:

Error:

```text
thread 'main' panicked at 'Failed to deploy indexer.: reqwest::Error { kind: Body, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(29987), path: "/api/index/fuel/tech_talk", query: None, fragment: None }, source: hyper::Error(ChannelClosed) }', plugins/forc-index/src/ops/forc_index_deploy.rs:114:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by rvmelkonian** [comment]
I can't reproduce, the plugin commands are working locally for me.

**Comment by ra0x3** [comment]
@deekerno When you get some time could you try this out? Would be super great if this was just a me problem. Again, I only see the issue in a specific context.

**Comment by ra0x3** [comment]
- Synced with @lostman and confirming that this issue is somehow due to the `--embedded-database` flag being passed. 
- In the mean time, users can just _not_ use the `--embedded-database` when trying to start their indexer

**Comment by ra0x3** [comment]
Reopening as someone recently ran into this again when following the Quickstart. It seems related to `--embedded-database` still

**Comment by ra0x3** [comment]
High priority because several users are trying to run the Quickstart, but can't 🙄

**Comment by ra0x3** [comment]
This issue is not fixed. Several users still having the problem:

- [Nick's issue on Slack](https://fuellabs.slack.com/archives/C04BQKYTJQJ/p1689092967618109)
- https://github.com/FuelLabs/fuel-indexer/issues/1070

**Comment by ra0x3** [comment]
Per https://github.com/seanmonstar/reqwest/issues/1808 I think we should swap our usage of `reqwest` in the plugin for a different HTTP client
