### ISSUE TITLE
Make our tests more succinct

### ISSUE THREAD

**Issue by rvmelkonian** [FuelLabs/fuel-indexer#826]
There are a lot of lines in our test code that repeat, mostly when we do the generation parts of the tests. For examples this block:
```rust
    let mut manifest = Manifest::try_from(assets::FUEL_INDEXER_TEST_MANIFEST).unwrap();
    update_test_manifest_asset_paths(&mut manifest);    
    srvc.register_index_from_manifest(manifest).await.unwrap();
    let mut conn = test_db.pool.acquire().await.unwrap();
```
And this:
```rust
    let contract = connect_to_deployed_contract().await.unwrap();
    let app = test::init_service(app(contract)).await;
    let req = test::TestRequest::post().uri("/ping").to_request();
    let _ = app.call(req).await;
```
These could be abstracted away into a helper function to make our tests more readable and less verbose. It's repeating logic. The url string passed into `post().uri` above, can just be an arg into a helper function.

**Comment by ra0x3** [comment]
Would be great if we could get something like:

```rust
struct TestScaffold {
  contract: Contract,
  app: AxumApp,
  req: TestRequest,
}

fn do_a_test() {
  let TestScaffold { contract, app, req, .. } = scaffold_test_stuff().await.unwrap();
}
```
Where `scaffold_test_stuff` would scaffold _everything_ (manifest, contract, app, request, service, connection, etc).

Or just something that contains all of this stuff in a single line (without too much abstraction)

**Comment by tibi77** [comment]
hey! why would we not do this inside the setup_test_components function? as far as i see the lines of code mentioned are always used in relationship with that function

**Comment by rvmelkonian** [comment]
Hey @tibi77! You could certainly do that, I think @ra0x3 was suggesting a slightly more radical redesign of the testing api, in order to make the code more ergonomic and cleaner.

**Comment by ra0x3** [comment]
Done in https://github.com/FuelLabs/fuel-indexer/pull/1126
