### ISSUE TITLE
Move all user-facing indexer components into `fuel-indexer-utils`

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#867]
- As of today users have to import [a few external crates](https://github.com/FuelLabs/fuel-indexer/blob/master/plugins/forc-index/src/utils/defaults.rs#L51) when building indexers
- Further, we have [a set of utility functions that users can use to improve indexer devx](https://github.com/FuelLabs/fuel-indexer/blob/master/packages/fuel-indexer-lib/src/utils.rs#L219)
- We should move all of this (as much as possible into `fuel-indexer-utils`
  - Crate already reserved https://crates.io/crates/fuel-indexer-utils
- `fuel-indexer-{macros, schema, plugin}`, should be re-exported if possible
  - Debating on whether or not we should just add `fuels` and `fuel-tx` as well
  - Open to having a discussion on this 
- The utility functions should be exported accordingly
- New exports should export a `prelude` mod where we export common things (as per the convention)

Additional context
- We should rust-doc _this entire crate_ before merging
  - The entire purpose of it is to provide a single interface for users to reference when building indexers

**Comment by deekerno** [comment]
I think it would be prudent to add `fuels` and `fuel-tx` in such a crate; by doing so, users wouldn't have to add them to their `Cargo.toml` and we would prevent situations in which we're on a particular version while a user pulls down a different version.
