### ISSUE TITLE
Fix nullable foreign keys

### ISSUE THREAD

**Issue by deekerno** [FuelLabs/fuel-indexer#874]
Long ago in a distant time (two months ago), I left this comment:

```
# TODO: Fix nullable foreign keys; there seems to be issues during codegen
type BookClub {
    id: ID!
    book: Book!
    member: Person!
    corporate_sponsor: Sponsor! @join(on:name)
}
```

There was indeed an issue during code generation, and @Braqzen is running into it. We should allow for this practice in an indexer.

**Comment by ra0x3** [comment]
I agree that nullable foreign keys should be allowed. Hoping this might be the fix for Syd. Let's base this potential PR on `feature/fuel-explorer`
