### ISSUE TITLE
Should we have a single indexer config?

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#89]
- We currently use a few configuration files to run an indexer
  - A node config ([example](https://github.com/FuelLabs/fuel-indexer/blob/master/examples/simple-non-wasm/config.yaml))
  - An executor config ([example](https://github.com/FuelLabs/fuel-indexer/blob/master/examples/simple-wasm/manifest.yaml))
  - An api_server config ([example](https://github.com/FuelLabs/fuel-indexer/blob/master/api_server/configs/pg_config.yaml))
 
- Should we merge all these configs into a single `config.yaml` in the `fuel-indexer/` root?
  - Pros:
    - Users would just have to update a single file for config changes
    - Could neatly partition each config section into parts (e.g., "database", "api_server", etc)
  - Cons:
    - Config file might be slightly large once we get all the options in there (I'm personally OK with this)
    - [Insert other cons...]

Additional context
- Mdbook would have to be update according to whatever is decided
- [See this PR comment](https://github.com/FuelLabs/fuel-indexer/pull/108#discussion_r915438840)
  - We should use default paths for the config, the user can specify a config path if it's outside the default location

**Comment by ra0x3** [comment]
CC @tjsharp1 @mitchmindtree @JoshuaBatty @SilentCicero for comments

**Comment by adlerjohn** [comment]
Since the indexer can run without contract source code/Forc, _requiring_ configuration of the indexer to live in `Forc.toml` doesn't make sense. It can be added _optionally_ later.

**Comment by Voxelot** [comment]
Would it also make sense to allow for dynamic configuration of the indexer to hot-reload wasm modules without downtime?

**Comment by ra0x3** [comment]
> Would it also make sense to allow for dynamic configuration of the indexer to hot-reload wasm modules without downtime?
- +1 on being able to update the config and restart the process(es) with little-to-no downtime
- But I'm thinking, would that be the responsibility of the user? Meaning, outside the scope of the indexer?
  - **Example:** 
    - If I'm running the indexer as a `systemd` process, I would just update my config file (whether that be new WASM module paths, new database config, etc). From there I'd just `systemctl restart fuel-indexer` (or whatever)
- So I guess my question is, how much of that restarting/reloading/etc is the responsibility of the indexer versus the responsibility of the user and whatever service manager they're using? (systemd in this case)

**Comment by Voxelot** [comment]
I was thinking more along the lines of a fuel-indexer managed config store, that users could make authenticated API requests against to deploy new wasm or update manifest configs.

However, given the indexer is likely to be a separate process from the grapqhl endpoints, restarting the indexer process with new service configs wouldn't really be downtime (just staleness).

**Comment by mitchmindtree** [comment]
> Since the indexer can run without contract source code/Forc, requiring configuration of the indexer to live in Forc.toml doesn't make sense. It can be added optionally later.

:heavy_plus_sign: :heavy_plus_sign:  We should solve indexer configuration in a dedicated file first, and then potentially for hosting this configuration under a `Forc.toml`'s metadata table later on if we decide it makes sense.

I've opened a proposal on how to handle customisable configuration in `Forc.toml` for 3rd-party plugins and external tools here:

https://github.com/FuelLabs/sway/issues/2180

If we intend to potentially allow for hosting this configuration under the `Forc.toml` (as mentioned in https://github.com/FuelLabs/sway/issues/2180), it may be worth considering the TOML format for the indexer's dedicated configuration. This would allow users to trivially move configuration between a dedicated indexer configuration and the `Forc.toml` `[metadata]` table.

Preferring TOML might also be worth considering just for a more consistent "Fuel ecosystem" experience in general, considering the `Forc.toml` and `Forc.lock` already set a bit of a precedent for this. That said, we may have other tools that are already configured with `yaml` that I'm unaware of - there's so much stuff going on under FuelLabs :smiling_face_with_tear:

**Comment by Voxelot** [comment]
Since an indexer may support many many apps, each with their own Forc.toml, it seems like it would make sense to have the indexer ingest a directory of manifests, rather than a monolithic config file. 

Configuring indexer logic from a Forc.toml may be a useful tool for local dev, but should probably be treated as high-level config used to dynamically generate the proper app indexer manifest. This generated manigest will need to incorporate the deployed contract id and other post-compilation network parameters, and will be deployment / environment specific.
