### ISSUE TITLE
Implement GraphQL query params

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#903]
- Per https://github.com/graphql/graphql-spec#query-syntax
- We should also support the ability to add params to a GraphQL query 
- Should be pretty straightforward to extract these from the request and pass them to the query-parser/sql

**Comment by rvmelkonian** [comment]
Hesitant to add this into our current `graphql-parser` api while `async-graphql` is being added, to avoid a similar situation as a few weeks ago. @deekerno Hold on this until [https://github.com/FuelLabs/fuel-indexer/pull/877](https://github.com/FuelLabs/fuel-indexer/pull/877) get's merged? Probably async-graphql gives us this out of the box.

**Comment by deekerno** [comment]
`async-graphql` does allow for this, and it may be partially addressed by #822.

**Comment by ra0x3** [comment]
Closing this until we get a unified GraphQL solution that solves https://github.com/FuelLabs/fuel-indexer/issues/1145
