### ISSUE TITLE
Add support for logical operators in introspection

### ISSUE THREAD

**Issue by deekerno** [FuelLabs/fuel-indexer#917]
Once #877 lands, we'll have auto-generated introspection functionality for user-generated schema. However, support for logical operators in the introspection was not added. We should add it into the dynamic schema generation so that users will be able to find that capability in the auto-generated documentation.

**Comment by ra0x3** [comment]
Closing this until we get a unified GraphQL solution that solves https://github.com/FuelLabs/fuel-indexer/issues/1145
