### ISSUE TITLE
Calculate `u64` value from the hash of a struct's fields

### ISSUE THREAD

**Issue by deekerno** [FuelLabs/fuel-indexer#951]
A user should be able to automatically create an ID for a struct based on the content of a struct.

**Comment by ra0x3** [comment]
And however we calculate this ID - it should factor in the type name as well

```text
$STRUCT_ID = f($STRUCT_TYPE_ID + $STRUCT_CONTENT)
```

**Comment by deekerno** [comment]
@ra0x3, @lostman: I have some stuff that already works for `hello-indexer` on `deekerno/951-auto-calc-u64-id`; it may be worth continuing with it but keep in mind that there will need to be a lot of manual testing to get the types right.
