### ISSUE TITLE
Logs not appearing for handlers other than "fn handle_block(block: BlockData)"

### ISSUE THREAD

**Issue by chlenc** [FuelLabs/fuel-indexer#964]
# Issue: Logs not appearing for handlers other than `handle_block`

## Description:

I have implemented an indexer that consists of multiple handlers, including `handle_block`, `handle_log_data`, `handle_call`, and others. However, I am only able to see logs from the `handle_block` handler. Logs from the other handlers are not being displayed. 

## Code:

```rust
extern crate alloc;
use fuel_indexer_macros::indexer;
use fuel_indexer_plugin::types::BlockData;
use fuel_indexer_plugin::utils::first8_bytes_to_u64;

const PROXY: &str = "0x8924a38ac11879670de1d0898c373beb1e35dca974c4cab8a70819322f6bd9c4";

#[indexer(manifest = "spark_indexer.manifest.yaml")]
pub mod compolabs_index_mod {

   fn handle_block(block: BlockData) {
        let height = block.height;
        let txs = block.transactions.len();
        Logger::info(&format!("🧱 Block height: {height} | transacrions: {txs}"));
        // ...some code
    }
    
    fn handle_log_data(data: ProxySendFundsToPredicateParams) {
        Logger::info(format!("✨ ProxySendFundsToPredicateParams \n{:?}", data).as_str());
    }

    fn handle_call(call: Call) {
        Logger::info(format!("🤙 Call \n{:?}", call).as_str());
    }

    fn handle_log(log: Log) {
        Logger::info(format!("📝 Log \n{:?}", log).as_str());
    }

    fn handle_transfer(transfer: Transfer) {
        Logger::info(format!("💸 Transfer \n{:?}", transfer).as_str());
    }

    fn handle_transferout(transfer_out: TransferOut) {
        Logger::info(format!("🍃 TransferOut \n{:?}", transfer_out).as_str());
    }
}
```

## Manifest file:

```yaml
---
namespace: compolabs
abi: "./proxy-contract-abi.json"
identifier: spark_indexer
fuel_client: ~
graphql_schema: schema/spark_indexer.schema.graphql
module:
  wasm: target/wasm32-unknown-unknown/release/spark_indexer.wasm
metrics: ~
contract_id: "0x8924a38ac11879670de1d0898c373beb1e35dca974c4cab8a70819322f6bd9c4"
start_block: 844540
end_block: ~
resumable: ~
```

### 1. Clone the repository

Clone the repository to your local machine, navigate to the project folder, and `git checkout` to the `fuel-indexer` branch:

```shell
git clone https://github.com/compolabs/spark-indexer.git
cd spark-indexer
git checkout fuel-indexer
```

### 2. Build and deploy the indexer

In this step, you will build and deploy the Fuel Indexer. Perform the following actions:

- Switch to version 0.15.0 of the indexer.
- Run a Postgres container:

```shell
docker run -d -p 5432:5432 --name my-postgres -e POSTGRES_PASSWORD=mysecretpassword postgres
```

- Start the Fuel Indexer service, connecting it to the beta-3 network:

```shell
fuel-indexer run --run-migrations --fuel-node-host beta-3.fuel.network --fuel-node-port 80 --postgres-host 127.0.0.1 --postgres-port 5432 --postgres-password mysecretpassword --postgres-user postgres
```

- Deploy the indexer by opening a new terminal tab in the `spark-indexer` directory:

- You can found tx with `ProxySendFundsToPredicateParams` log on `start_block: 810009`

```shell
forc index build
# If you encounter any build errors, try running the following two lines:
# export AR=/opt/homebrew/opt/llvm/bin/llvm-ar 
# export CC=/opt/homebrew/opt/llvm/bin/clang
forc index deploy
```

## Resources
- [Spark indexer repo](https://github.com/compolabs/spark-indexer/tree/fuel-indexer)
- [Fuel Indexer Documentation](https://fuellabs.github.io/fuel-indexer)

1. Set up the indexer with the provided code and manifest file.
2. Trigger events that should invoke the `handle_log_data`, `handle_call`, and other handlers.
3. Observe that logs are only being displayed for the `handle_block` handler, while logs from other handlers are missing.

**Expected behavior:**

Logs should be displayed for all handlers (`handle_log_data`, `handle_call`, etc.) as defined in the code.

**Additional information:**

- I have verified that the events triggering the other handlers are being processed correctly.
- I have checked the logging configuration and ensured that all handlers are set up to log messages.

**Environment:**
- Toolchain version:
```
>>> fuelup show      
Default host: aarch64-apple-darwin
fuelup home: /Users/alexey/.fuelup

installed toolchains
--------------------
beta-3-aarch64-apple-darwin
latest-aarch64-apple-darwin
forc-0.39-toolchain (default)

active toolchain
-----------------
forc-0.39-toolchain (default)
  forc : 0.39.0
    - forc-client
      - forc-deploy : 0.39.0
      - forc-run : 0.39.0
    - forc-doc : 0.39.0
    - forc-explore - not found
    - forc-fmt : 0.39.0
    - forc-index : 0.15.0
    - forc-lsp : 0.39.0
    - forc-tx : 0.39.0
    - forc-wallet : 0.2.2
  fuel-core : 0.17.11
  fuel-indexer : 0.15.0

fuels versions
---------------
forc : 0.39
```
- Operating system: MacOS Monterey 12.6
- Rust version: rustup 1.26.0

---

Feel free to modify the text as needed and add any additional details that you think are relevant to the issue.

**Comment by chlenc** [comment]
Spark indexer code you can find here
https://github.com/compolabs/spark-indexer/tree/fuel-indexer

**Comment by ra0x3** [comment]
@chlenc 
- I copied and pasted your indexer ☝🏽 into [our test indexer](https://github.com/FuelLabs/fuel-indexer/blob/master/packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs)
- As I'm triggering events, I see that the handlers are getting called

```text
2023-06-01T16:05:14.772116Z  INFO fuel_indexer::database: 49: Connection stashed as: Some(Postgres(PoolConnection))
2023-06-01T16:05:14.772732Z  INFO fuel_indexer::ffi: 110: 🧱 Block height: 6 | transacrions: 2
2023-06-01T16:05:14.772828Z  INFO fuel_indexer::ffi: 110: 🧱 Block height: 6 | transacrions: 2
2023-06-01T16:05:14.772862Z  INFO fuel_indexer::ffi: 110: 🤙 Call
Call { contract_id: 0000000000000000000000000000000000000000000000000000000000000000, to: d1ece60c4653e20bcf0a70c449c6e2c90731c6b78d7bd40bab16ffeb595f3150, amount: 1000000, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 1000, fn_name: "trigger_transfer" }
2023-06-01T16:05:14.772890Z  INFO fuel_indexer::ffi: 110: 💸 Transfer
Transfer { contract_id: d1ece60c4653e20bcf0a70c449c6e2c90731c6b78d7bd40bab16ffeb595f3150, to: d1ece60c4653e20bcf0a70c449c6e2c90731c6b78d7bd40bab16ffeb595f3150, amount: 1, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, pc: 13584, is: 11624 }
```
- Which makes me believe that your contract is not emitting any events.
- Are you sure that:
  1. Your contract is emitting actual receipts?
  2. You're subscribed to the correct contract?

CC @deekerno

**Comment by chlenc** [comment]
ii.  Is it ok way to provide `contract_id`, or I should paste it in `fuel...` format?
```
contract_id: "0x8924a38ac11879670de1d0898c373beb1e35dca974c4cab8a70819322f6bd9c4"
```

**Comment by chlenc** [comment]
> @chlenc
> 
> * I copied and pasted your indexer ☝🏽 into [our test indexer](https://github.com/FuelLabs/fuel-indexer/blob/master/packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs)
> * As I'm triggering events, I see that the handlers are getting called
> 
> ```
> 2023-06-01T16:05:14.772116Z  INFO fuel_indexer::database: 49: Connection stashed as: Some(Postgres(PoolConnection))
> 2023-06-01T16:05:14.772732Z  INFO fuel_indexer::ffi: 110: 🧱 Block height: 6 | transacrions: 2
> 2023-06-01T16:05:14.772828Z  INFO fuel_indexer::ffi: 110: 🧱 Block height: 6 | transacrions: 2
> 2023-06-01T16:05:14.772862Z  INFO fuel_indexer::ffi: 110: 🤙 Call
> Call { contract_id: 0000000000000000000000000000000000000000000000000000000000000000, to: d1ece60c4653e20bcf0a70c449c6e2c90731c6b78d7bd40bab16ffeb595f3150, amount: 1000000, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 1000, fn_name: "trigger_transfer" }
> 2023-06-01T16:05:14.772890Z  INFO fuel_indexer::ffi: 110: 💸 Transfer
> Transfer { contract_id: d1ece60c4653e20bcf0a70c449c6e2c90731c6b78d7bd40bab16ffeb595f3150, to: d1ece60c4653e20bcf0a70c449c6e2c90731c6b78d7bd40bab16ffeb595f3150, amount: 1, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, pc: 13584, is: 11624 }
> ```
> 
> * Which makes me believe that your contract is not emitting any events.
> * Are you sure that:
>   
>   1. Your contract is emitting actual receipts?
>   2. You're subscribed to the correct contract?
> 
> CC @deekerno

Can you try to run my indexer?
Because I have no idea how to run your test indexer 😅

**Comment by ra0x3** [comment]
@chlenc 
- This is probably related to the same incorrect contract ID format in your indexer manifest.
  - Same as what we discussed in https://github.com/FuelLabs/fuel-indexer/issues/982
- Could you let me know if this is still an issue?
