### ISSUE TITLE
Fails to handle LogData when using the indexer

### ISSUE THREAD

**Issue by chlenc** [FuelLabs/fuel-indexer#982]
### Description
I am attempting to retrieve contract log data using the indexer according to the instructions provided in the [indexer reference guide](https://fuellabs.github.io/fuel-indexer/master/reference-guide/indexing/receipts/logdata.html#logdata). However, it seems that the `handle_log_data` function is not being called as expected.

I have created a simple indexer with two handlers defined in the `lib.rs` file of the `compolabs_index_mod` module. The `handle_block` handler is responsible for searching and printing `ProxySendFundsToPredicateParams` in the transaction receipts of each block. The `handle_log_data` function is intended to catch and print instances of the `ProxySendFundsToPredicateParams` type. I expected to see logs from both the `handle_block` and `handle_log_data` functions, but only the log from `handle_block` is appearing.

Here is the relevant code snippet:

```rust
extern crate alloc;
use fuel_indexer_utils::prelude::*;

const PROXY: &str = "0x8924a38ac11879670de1d0898c373beb1e35dca974c4cab8a70819322f6bd9c4";

#[indexer(manifest = "spark_indexer.manifest.yaml")]
pub mod compolabs_index_mod {

    fn handle_block(block: BlockData) {
        let height = block.height;
        let txs = block.transactions.len();
        let proxy_contract_id = ContractId::from_str(PROXY).unwrap();

        Logger::info(&format!("🧱 Block height: {} | transactions: {}", height, txs));

        for tx in block.transactions.clone() {
            match tx.status {
                fuel::TransactionStatus::Failure { .. } => continue,
                _ => (),
            }

            tx.receipts.iter().for_each(|receipt| {
                if receipt.data().is_some() {
                    let data = ProxySendFundsToPredicateParams::try_from(receipt.data().unwrap());
                    let id = receipt.id();
                    if data.is_ok() && id.is_some() && id.unwrap().to_owned() == proxy_contract_id {
                        Logger::info(&format!("📬 Order: {:#?}", data));
                    }
                }
            });
        }
    }

    fn handle_log_data(data: ProxySendFundsToPredicateParams) {
        Logger::info(format!("✨ ProxySendFundsToPredicateParams \n{:?}", data).as_str());
    }
}
```

### Expected Behavior
I expected to see logs from both the `handle_block` and `handle_log_data` functions when running the indexer.

### Actual Behavior
Only the log output from the `handle_block` function is appearing. The `handle_log_data` function does not seem to be called.

### Steps to Reproduce
0. Switch to the latest version of the indexer.
```shell
fuelup toolchain install latest   
fuelup default latest
```
1. Clone the repo and go to the `handle-log-data-issue` branch
```shell
 git clone https://github.com/compolabs/spark-indexer.git
 cd spark-indexer/   
 git checkout handle-log-data-issue
```
2. Run a postgres database in a docker container
```shell
docker run -d -p 5432:5432 --name my-postgres -e POSTGRES_PASSWORD=mysecretpassword postgres
```
3. Build and deploy the indexer
```shell
fuel-indexer run --run-migrations --fuel-node-host beta-3.fuel.network --fuel-node-port 80 --postgres-host 127.0.0.1 --postgres-port 5432 --postgres-password mysecretpassword --postgres-user postgres
```
4. Deploy the indexer by opening a new terminal tab in the root repo directory:
```shell
forc index deploy
```

### Environment
- Code source: [https://github.com/compolabs/spark-indexer/tree/handle-log-data-issue](https://github.com/compolabs/spark-indexer/tree/handle-log-data-issue)
- Docker Compose File: [https://github.com/compolabs/spark-indexer/blob/fuel-indexer/docker-compose.yaml](https://github.com/compolabs/spark-indexer/blob/fuel-indexer/docker-compose.yaml)
- Toolchain:
```
Default host: aarch64-apple-darwin
fuelup home: /Users/alexey/.fuelup

installed toolchains
--------------------
beta-3-aarch64-apple-darwin
latest-aarch64-apple-darwin (default)
forc-0.39-toolchain

active toolchain
-----------------
latest-aarch64-apple-darwin (default)
  forc : 0.40.1
    - forc-client
      - forc-deploy : 0.40.1
      - forc-run : 0.40.1
    - forc-doc : 0.40.1
    - forc-explore : 0.28.1
    - forc-fmt : 0.40.1
    - forc-index : 0.16.1
    - forc-lsp : 0.40.1
    - forc-tx : 0.40.1
    - forc-wallet : 0.2.2
  fuel-core : 0.18.1
  fuel-indexer : 0.16.1

fuels versions
---------------
forc : 0.42
```

[foo.txt](https://github.com/FuelLabs/fuel-indexer/files/11666573/foo.txt)

**Comment by ra0x3** [comment]
@chlenc 
- You're not seeing your handler be called most likely because it only gets called if there is data for it to handle
- I'm almost certain that `handle_log_data` isn't called because it never gets a `ProxySendFundsToPredicateParams` to handle
- In order to test this, you can just see if you ever see a `Receipt::LogData`
  - My hunch is, you won't see any logs in this handler because no `LogData` receipt is ever produced

- @chlenc  to debug this, update your indexer to the following, rebuild, redeploy and see if you ever see the `"I found a LogData receipt!"` log
  - If you don't see this log message when you call your contract, then your contract is not emitting `LogData` receipts

```rust
extern crate alloc;
use fuel_indexer_utils::prelude::*;

const PROXY: &str = "0x8924a38ac11879670de1d0898c373beb1e35dca974c4cab8a70819322f6bd9c4";

#[indexer(manifest = "spark_indexer.manifest.yaml")]
pub mod compolabs_index_mod {

    fn handle_block(block_data: BlockData) {
        // do stuff...
    }

    fn handle_log_data(block: BlockData) {
        Logger::info("I found a block!");
        for transaction in block_data.transactions.iter() {
            for receipt in transaction.receipts.iter() {
                match receipt {
                    fuel::Receipt::LogData { .. } => {
                        Logger::info("I found a LogData receipt!");
                    }
                    _ => {
                        Logger::info("Not handling this receipt type.");
                    }
                }
            }
        }
    }
}
```

**Comment by ra0x3** [comment]
@chlenc 
- Could you show us your expanded indexer?
- You will have to:
  - [ ] Switch to nightly `rustup override set nightly-aarch64-apple-darwin`
  - [ ] Go to your indexer root `cd /path/to/my-indexer`
  - [ ] Expand your module `cargo rustc --profile=check -- -Zunpretty=expanded > foo.txt`
  - [ ] Upload `foo.txt` to this issue

**Comment by chlenc** [comment]
Awesome!
Seems to be there is LogData in some receipts. 
But `fn handle_log_data(block: BlockData)` looks more like a `handle_block` handler (I will use your version of code in my indexer because it is better 🤓), so the question more like how to make `fn handle_log_data(data: ProxySendFundsToPredicateParams)` works

Here is my contract log calling, maybe I'm doing something wrong here
https://github.com/compolabs/ethglobal-predicate/blob/58ac7ef13faaaf84cddfa7d199fa88be359834c8/proxy-contract/src/main.sw#L34

**Comment by ra0x3** [comment]
@chlenc Please upload your foo.txt file to this issue if you can

**Comment by chlenc** [comment]
It was here
<img width="202" alt="image" src="https://github.com/FuelLabs/fuel-indexer/assets/35231749/db699e27-854f-41b5-829f-b8dd648e298e">


Just click here 👇
[foo.txt](https://github.com/FuelLabs/fuel-indexer/files/11666536/foo.txt)

**Comment by ra0x3** [comment]
@chlenc 
- Hm. Your expanded code looks correct 👌🏽 
- Could you show me your indexer manifest file?

**Comment by chlenc** [comment]
> @chlenc
> 
> * Hm. Your expanded code looks correct 👌🏽
> * Could you show me your indexer manifest file?


https://github.com/compolabs/spark-indexer/blob/handle-log-data-issue/spark_indexer.manifest.yaml

**Comment by ra0x3** [comment]
@chlenc 
- I wonder if your contract subscription is working properly 🤔 
- As an experiment, try removing your contract ID filter
  - In your indexer manifest file, update your contract subscription to be `contract_id: ~`
- Make a small change to your indexer lib.rs module
  - If you try to rebuild your indexer without changing the lib.rs module, cargo will just use the cached indexer version
- So (1) Update your `contract_id` in your manifest ☝🏽 (2) add a small `Logger::info("foo");` to your indexer and rebuild
  - You just need to change some character in some string in order for `cargo` to not use the cached build

**Comment by chlenc** [comment]
> Is `handle_log_data2` being called?
Yes, it was called
So, I just tried to use `contract_id: fuel13yj28zkprpukwr0p6zyccdemav0rth9fwnzv4w98pqvnytmtm8zqanjtv8` in the manifest, but this time made a small change as you texted before, and it's worse for me

I guess the problem was in the contract_id type, we should use the `fuel..` format

**Comment by ra0x3** [comment]
@chlenc 
- Yes, you should use the `fuel` namespaces address
- I thought we handled both, but apparently not
- If you would like us to handle both types, feel free to open an issue (we will handle it from there).
- With that said, do you mind if I close this issue? Seems like everything has been resolved?

**Comment by chlenc** [comment]
Yes, you can close that, thanks a lot for your help 💙💚🧡
