### ISSUE TITLE
Spike for schema refactor

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#994]
- The `fuel-indexer-schema` and `fuel-indexer-macros` modules are used automagically create structs, types, and SQL tables for indexers
- These modules are some of the most important abstractions that we use
- `fuel_indexer_macros::schema` helps derive a bunch of rust types from graphql types
- `fuel_indexer_schema::db::tables` helps convert GraphQL schema into tables, create those tables, and persist a representation of those tables into the DB (for when schema is reloaded)
- However the schema module in `fuel-indexer-macros` and the tables module in `fuel-indexer-schema` are getting a bit crazy
  - We've improved them both a ton, but we've more so put bandaids on things rather than providing permanent fixes/improvements
    - This has been because of our time constraints
 - We should refactor the schema and tables module to make them less hacky and more idiomatic Rust-y
   - This will help a ton with dev productivity

- Below is my idea for how we should maybe think about refactoring these modules 
- This is really just pseudo-code to give an idea of what I'm referring to 
- We can update this and iterate on it, and when we feel like we're in a good place, we can create a feature branch and work on it there.
- If we end up doing this 👇🏽 we can probably combine `Schema` and `SchemaBuilder`

```rust
trait SQLFragment;

// object -> table
struct Table {
  name: String,
  columns: Vec<Column>,
  parser: GraphQLParser,
  sqlx_dtype: sqlx::types::postgres::BigInt;
}

impl Table {
    fn from_object(obj: &Object, parser: &GraphQLSchemParser) -> Self;
}

impl SQLFragment for Table {
    fn sql_frag(&self) -> String;
}

enum Constraint {
  Index(IndexConstraint),
  Fk(FkConstraint),
}

enum ColumnType {
  Normal,
  Virtual
}

// field -> column
struct Column {
   name: String,
   ft_column: FtColumn,
   constraints: Vec<Constraint>,
   col_type: ColumnType,
   parser: GraphQLParser
}

impl Column {
    fn from_field_def(f: FieldDefinition, parser: GraphQLSchemParser) -> Self;
}

impl SQLFragment for Column {
    fn sql_frag(&self) -> String;
}

impl From<sqlx::Row> for Column;

struct Decoder {
  type_id: i64,
  field_constructors: Vec<TokenStream>,
  field_extractors: Vec<TokenStream>,
  from_row_extractors: Vec<TokenStream>,
  to_row_extractors: Vec<TokenStream>,
  new_impl_fields: Vec<TokenStream>,
  // other stuff....
}

impl From<Decoder> for TokenStream;

impl Decoder {
  fn from_object(o: Object, schema: GraphQLSchemParser) -> Self;
}

fn process_type_def(
    schema: &mut ParsedGraphQLSchema,
    typ: &TypeDefinition,
) -> Option<proc_macro2::TokenStream> {
 let decoder = match &typ.kind {
    TypeKind::Object(o) => {
        Decoder::from_object(o, schema)?
    }
    TypeKind::Enum(e) => {
       Decoder::from_enum(e, schema)?
    }
    TypeKind::Union(u) => {
        Decoder::from_union(u, schema)
    }
  };

   Some(decoder.into())
}
```

`fuel_indexer_schema::db::tables` would work something like:

```rust

struct GraphQLSchema(String);

impl GraphQLSchemParser {
  pub fn version() -> String;
}

struct SchemaBuilder {
  namespace: String,
  identifier: String,
  columns: Vec<Column>,
  parser: GraphQLSchemParser,
}

impl SchemaBuilder {
  pub fn build() {
      let ast = BASE_SCHEMA;
      let parser = GraphQLSchemParser::from(&ast);
      let tables = parser.non_virtual_tables().map(|o| Table::from_object(o, &parser)).collect();
      let stmtnts = tables.map(|t| t.sql_frag()).collect();
      let _ = futures::run_all(*stmnts).await?;
  }
}

pub struct Schema {
  namespace: String,
  identifier: String,
  columns: Vec<Column>,
  parser: GraphQLSchemParser,
} 

impl Schema {
  pub fn load_from_db(&self) {
    let ast = BASE_SCHEMA;
    let parser = GraphQLSchemParser::from(&ast);
    let columns: Vec<Column> = load_columns(namespace, identifier).await?;
    // the rest...
  }
}
```

**Comment by ra0x3** [comment]
@deekerno Curious to get your thoughts here. Obviously a super pseudo-code WIP but hopefully you get the idea

**Comment by deekerno** [comment]
Yeah, I think this will be good. I've had to make a few adjustments myself while implementing list types and I don't want these two things to get more unwieldy than they already are.
